// AUTO-GENERATED from "M3 Research Burn/BurnR2_04_Interview_Intel_Batch2_2026-08-09.md".
// 12 Boston-area / SaaS employers, salvaged from the burn-r2-04 research run.
// Confidence tags are the report's own: [A] first-hand scrape, [B] aggregator paraphrase,
// [C] inference. Coach advice is attached once per company and is explicitly marked
// unverified — it is model-generated commentary, not sourced fact.
// Do not hand-edit; regenerate from the source report.
import type { Question } from './types';

const NOW = '2026-08-10T04:00:00.000Z';

const q = (
  id: string, text: string, type: Question['type'], competency: Question['competency'],
  company: string, difficulty: number, notes: string,
): Question => ({ id, text, type, competency, company, difficulty, notes, createdAt: NOW, updatedAt: NOW });

export const batch2Questions: Question[] = [
  q('qr204_wayfair_1', 'Y-on-Y Growth Rate（DataLemur 原文）', 'technical', 'data', 'Wayfair', 3, '来源 BurnR2_04（一手抓取 [A]）。`user_transactions(transaction_id, product_id, spend, transaction_date)`。写 SQL 输出每年每个 product 的 current_year_spend、prev_year_spend、yoy_rate (%)，保留 2 位小数。**正解骨架：** `LAG(spend) OVER (PARTITION BY product_id ORDER BY EXTRACT(YEAR FROM transaction_date))`。 ｜ 教练建议（M3 生成，未经核实，人名/校友人数一律不要当事实）：- Pricing 题要主动提"我想用 switchback design 而不是 user-level A/B，因为同一地区用户会互相竞争"——这是 Wayfair pricing 团队 2024 工程博客的真实方法。 - 5% 转化率下降题：先问"是北美整体还是只 App？""是 new vs returning？"，再切渠道。 - STAR 直接复用 Northeastern 的 **BART-MNLI 69%→82%** 那段（讲 how 优化 + 业务 impact 13pp），Wayfair 经理最爱"我能让 baseline 模型有 13pp lift"这种数据。 - visa：Wayfair 在 OPT 阶段很顺，H-1B sponsor 历史长，但近 2 年偏保守，准备好回答"我会在 2027 抽签季前拿到 STEM OPT extension"。'),
  q('qr204_wayfair_2', 'Monthly Average Rating per Product', 'technical', 'data', 'Wayfair', 3, '来源 BurnR2_04（一手抓取 [A]）。`reviews(review_id, user_id, submit_date, product_id, stars)`。`EXTRACT(MONTH FROM submit_date)` + `AVG(stars)` + `GROUP BY mth, product`。'),
  q('qr204_wayfair_3', 'Optimize Slow Clickstream Query', 'technical', 'data', 'Wayfair', 3, '来源 BurnR2_04（一手抓取 [A]）。（Hard）：给出"数百万行 clickstream"场景，要 candidate 列出 5 条提速原则（只 select 必要列、加索引、明确 join 类型、选对数据类型、避免 `SELECT *`）。Dataford 标 Hard。'),
  q('qr204_wayfair_5', 'Checkout Funnel Drop-off', 'technical', 'data', 'Wayfair', 3, '来源 BurnR2_04（一手抓取 [A]）。从 `user_web_sessions` 算每一阶段 drop-off rate。'),
  q('qr204_wayfair_6', 'Coffee Maker 定价', 'case', 'strategy', 'Wayfair', 3, '来源 BurnR2_04（一手抓取 [A]）。（product case）：高度竞争品定价的 A/B 实验设计——primary metric, secondary, guardrail, sample size, runtime。'),
  q('qr204_wayfair_7', '5% WoW 转化率下降诊断', 'case', 'strategy', 'Wayfair', 3, '来源 BurnR2_04（一手抓取 [A]）。（diagnostic case）：按"内部 / 外部 / 渠道 / 商品 / 漏斗阶段"5 维度分诊。'),
  q('qr204_wayfair_8', 'Supplier Logistics Portal KPI 设计', 'case', 'strategy', 'Wayfair', 3, '来源 BurnR2_04（一手抓取 [A]）。（product analytics）：从 on-time delivery rate、damage rate、return rate 三个指标体系出发，描述每条线如何拆解。'),
  q('qr204_hubspot_1', 'RANK vs DENSE_RANK vs ROW_NUMBER', 'technical', 'data', 'HubSpot', 3, '来源 BurnR2_04（一手抓取 [A]）。分别举例 HubSpot user 升级层级的场景。 ｜ 教练建议（M3 生成，未经核实，人名/校友人数一律不要当事实）：HubSpot 是 Northeastern 校友聚集地，2 个 alumni 在里面做 PM/DA。面试官问"为什么 SaaS"时要提 Flywheel + HEART 框架 + 你想"做能让 20 万 SMB 直接用上的数据产品"。CTE + 窗口函数必须写得行云流水——HubSpot 出的 take-home 经常 6 个问题里有 4 个是窗口函数。'),
  q('qr204_hubspot_2', 'MAU 升级 + MoM 增长率', 'technical', 'data', 'HubSpot', 3, '来源 BurnR2_04（一手抓取 [A]）。`subscriptions(user_id, tier, upgrade_date)`——计算每个月升级人数的环比。'),
  q('qr204_hubspot_3', 'Rolling 7-day sign-up 平均', 'technical', 'data', 'HubSpot', 3, '来源 BurnR2_04（一手抓取 [A]）。（CTE + 窗口）：`signups(signup_date, user_id)` → `AVG() OVER (ORDER BY signup_date ROWS BETWEEN 6 PRECEDING AND CURRENT ROW)`。'),
  q('qr204_hubspot_4', '大表上 multiple heavy joins 优化', 'technical', 'data', 'HubSpot', 3, '来源 BurnR2_04（一手抓取 [A]）。（Hard）：分区、列裁剪、谓词下推、join 顺序、statistics、materialized view。'),
  q('qr204_hubspot_5', '5% 邮件 engagement 下降诊断', 'case', 'strategy', 'HubSpot', 3, '来源 BurnR2_04（一手抓取 [A]）。（product case）：从 send-time / subject-line / deliverability / audience segment / product change 5 维度拆。'),
  q('qr204_hubspot_6', '设计 A/B 测 onboarding flow', 'case', 'strategy', 'HubSpot', 3, '来源 BurnR2_04（一手抓取 [A]）。（product case）：primary = activation rate，guardrail = support tickets，runtime 2 周，min detectable lift 3%，power 0.8。'),
  q('qr204_hubspot_7', '新 CRM feature 成功 metrics', 'case', 'strategy', 'HubSpot', 3, '来源 BurnR2_04（一手抓取 [A]）。（product case）：adoption、retention lift、revenue per seat、support deflection。'),
  q('qr204_hubspot_8', 'Retention dashboard 应包含什么', 'case', 'strategy', 'HubSpot', 3, '来源 BurnR2_04（一手抓取 [A]）。（product case）：cohort retention heatmap, DAU/WAU/MAU stickiness, feature usage breakdown, churn reason pie, NRR by segment。'),
  q('qr204_toast_1', 'LEFT vs INNER JOIN 业务场景', 'technical', 'data', 'Toast', 3, '来源 BurnR2_04（一手抓取 [A]）。举例 Toast 餐厅订单 + 退款表，说明用错会少算 revenue。 ｜ 教练建议（M3 生成，未经核实，人名/校友人数一律不要当事实）：Toast 极度重视 "you actually know the restaurant industry"——面试前 30 分钟一定要去读 Toast Engineering Blog 和他们 2025 年报里的 KPI 框架。Take-home 大概率是"设计 dashboard for restaurant owner 视角的 KPIs"，Zihao 准备一份 mock 即可复用到 5 家公司。'),
  q('qr204_toast_2', 'Churn rate + segment', 'technical', 'data', 'Toast', 3, '来源 BurnR2_04（一手抓取 [A]）。`restaurants(restaurant_id, signup_date, churn_date, plan_tier)`，按城市/plan_tier/GMV 段切 churn。'),
  q('qr204_toast_3', '数据收集与清洗流程', 'technical', 'data', 'Toast', 3, '来源 BurnR2_04（一手抓取 [A]）。（process）：从 POS → Kafka → S3 → Snowflake → dbt mart，描述每一步如何应对脏数据。'),
  q('qr204_toast_4', 'CTE / 窗口结构化大表 join', 'technical', 'data', 'Toast', 3, '来源 BurnR2_04（一手抓取 [A]）。fact_orders + dim_restaurant + dim_menu，3 张表 join 算每个 restaurant 的月 GMV + WoW delta。'),
  q('qr204_toast_5', '新功能 success metrics', 'case', 'strategy', 'Toast', 3, '来源 BurnR2_04（一手抓取 [A]）。（product case）：Toast Payroll 上线，指标 = active restaurant adoption %、payroll 错误率、餐厅 GMV 变化、CSAT。'),
  q('qr204_toast_6', '非技术 stakeholder 翻译复杂分析', 'case', 'strategy', 'Toast', 3, '来源 BurnR2_04（一手抓取 [A]）。（behavioral）：你用 SaaS metrics 术语跟 restaurant owner 沟通时怎么翻译。'),
  q('qr204_toast_7', '判断 metric 异常 vs 长期趋势', 'case', 'strategy', 'Toast', 3, '来源 BurnR2_04（一手抓取 [A]）。（statistics/analysis）：周环比 vs 同比、季节性调整、Bayesian change-point。'),
  q('qr204_toast_8', '"你入职 Toast 第一周会做什么"', 'case', 'strategy', 'Toast', 3, '来源 BurnR2_04（一手抓取 [A]）。（role-alignment）：认识 stakeholder、读 dbt docs、看 lineage、跑一个 kitchen-test dashboard。'),
  q('qr204_draftkings_1', 'Top 5 players by total earnings', 'technical', 'data', 'DraftKings', 3, '来源 BurnR2_04（论坛/聚合转述 [B]）。`fantasy_leagues(player_id, season, earnings)` → `RANK() OVER (ORDER BY earnings DESC) WHERE rank<=5`。 ｜ 教练建议（M3 生成，未经核实，人名/校友人数一律不要当事实）：DraftKings 对 Northeastern 校友友好，2 个 MSDS 校友在 risk team。**最关键的隐藏考点是 expected value**——Zihao 在 Northeastern 学过 Probability (ALY 6010/6020)，把 EV、CLT、Bayesian update 都备熟就行。Case 准备"如果你 4 倍 entry fee 的 contest 只 fill 30%，你怎么办"——这类填空情境题。'),
  q('qr204_draftkings_2', 'Expected value 在 gaming 决策', 'technical', 'data', 'DraftKings', 3, '来源 BurnR2_04（论坛/聚合转述 [B]）。（concept）：EV = Σ(p_i × payout_i) – cost，DraftKings Sportsbook pricing 时如何用 EV 设 line。'),
  q('qr204_draftkings_3', 'Marketing campaign effectiveness 统计', 'technical', 'data', 'DraftKings', 3, '来源 BurnR2_04（论坛/聚合转述 [B]）。t-test、z-test、p-value、置信区间、sample size 算 power。'),
  q('qr204_draftkings_4', '缺失值处理', 'technical', 'data', 'DraftKings', 3, '来源 BurnR2_04（论坛/聚合转述 [B]）。listwise deletion、mean/median imputation、model-based (MICE)、缺失模式分类（MCAR/MAR/MNAR）。'),
  q('qr204_draftkings_5', 'Sizing a contest for a new fantasy game', 'case', 'strategy', 'DraftKings', 3, '来源 BurnR2_04（论坛/聚合转述 [B]）。（case）：prize pool ↔ entry fee ↔ rake ↔ participation rate，给一个 target GGR 反推 prize pool。'),
  q('qr204_draftkings_6', 'Public transportation customer dissatisfaction case', 'case', 'strategy', 'DraftKings', 3, '来源 BurnR2_04（论坛/聚合转述 [B]）。（structured case）：如何 break down、定义 north star、生成 hypotheses。'),
  q('qr204_draftkings_7', '用数据推动业务决策的真实故事', 'case', 'strategy', 'DraftKings', 3, '来源 BurnR2_04（论坛/聚合转述 [B]）。（behavioral + case）。'),
  q('qr204_draftkings_8', 'clustered vs non-clustered index', 'technical', 'data', 'DraftKings', 3, '来源 BurnR2_04（论坛/聚合转述 [B]）。（technical SQL knowledge）。'),
  q('qr204_cargurus_1', 'Top reps by monthly revenue', 'technical', 'data', 'CarGurus', 3, '来源 BurnR2_04（一手抓取 [A]）。（Medium）：`sales(sale_id, rep_id, sale_date, amount)` → `RANK() OVER (PARTITION BY month ORDER BY revenue DESC)`。 ｜ 教练建议（M3 生成，未经核实，人名/校友人数一律不要当事实）：CarGurus DA 中有相当一部分时间在维护 commission 系统——他们喜欢"数据 + 系统设计"复合能力题。Zihao 在 Northeastern 选过 Database (ALY 6110) 的话，把 star schema 和 SCD Type 2 概念准备一下有奇效。'),
  q('qr204_cargurus_2', 'Rolling 3-month average 订阅', 'technical', 'data', 'CarGurus', 3, '来源 BurnR2_04（一手抓取 [A]）。（Medium）：`dealer_subscriptions(dealer_id, month, active)` → `AVG(active) OVER (ORDER BY month ROWS BETWEEN 2 PRECEDING AND CURRENT ROW)`。'),
  q('qr204_cargurus_3', 'NULL + 数据不匹配时如何 join 两张大表', 'technical', 'data', 'CarGurus', 3, '来源 BurnR2_04（一手抓取 [A]）。（Hard）：coalesce、IS NULL check、outer apply、左反 join。'),
  q('qr204_cargurus_4', 'LEFT JOIN vs INNER JOIN + commission 错算场景', 'technical', 'data', 'CarGurus', 3, '来源 BurnR2_04（一手抓取 [A]）。（Medium）。'),
  q('qr204_cargurus_5', '多层级 commission schema 设计', 'technical', 'data', 'CarGurus', 3, '来源 BurnR2_04（一手抓取 [A]）。（Hard / modeling）：fact_sale + dim_rep_hierarchy + dim_commission_plan，star schema，季度切换版本。'),
  q('qr204_cargurus_6', 'CRM vs finance 库 diff', 'technical', 'data', 'CarGurus', 3, '来源 BurnR2_04（一手抓取 [A]）。（Medium）：如何 reconcile、root cause analysis。'),
  q('qr204_cargurus_7', 'Rep 投诉 quarterly commission 不对', 'technical', 'data', 'CarGurus', 3, '来源 BurnR2_04（一手抓取 [A]）。（Medium / process）：step 1 拉 commission calc SQL、step 2 跟 plan 文档对、step 3 找上游源头、step 4 出 RCA。'),
  q('qr204_cargurus_8', 'multi-team split opportunity 防 double-counting', 'technical', 'data', 'CarGurus', 3, '来源 BurnR2_04（一手抓取 [A]）。（Medium / data integrity）：allocation_pct 表 + assert SUM = 1.0。'),
  q('qr204_chewy_1', 'Top 10 products last quarter', 'technical', 'data', 'Chewy', 3, '来源 BurnR2_04（一手抓取 [A]）。`order_items(order_id, product_id, qty, sale_date)` → `SUM(qty)` + `RANK() OVER (ORDER BY sum DESC) LIMIT 10`。 ｜ 教练建议（M3 生成，未经核实，人名/校友人数一律不要当事实）：Chewy 面试偏简单，但**文化题权重大**——Zihao 准备一份"我为 Northeastern 同学做的 service"类故事。Boston 办公室在 Hyde Park，离 Northeastern 30 分钟地铁，方便 onsite。'),
  q('qr204_chewy_2', 'Customer purchase trend + recommendations', 'technical', 'data', 'Chewy', 3, '来源 BurnR2_04（一手抓取 [A]）。（Medium）：RFM 段、category affinity。'),
  q('qr204_chewy_3', 'Supervised vs Unsupervised learning', 'technical', 'data', 'Chewy', 3, '来源 BurnR2_04（一手抓取 [A]）。概念 + Chewy 例子（churn 预测 = supervised；产品聚类 = unsupervised）。'),
  q('qr204_chewy_4', 'SQL 优化慢 query', 'technical', 'data', 'Chewy', 3, '来源 BurnR2_04（一手抓取 [A]）。（Hard）：见 Wayfair Q3 通用 5 条原则。'),
  q('qr204_chewy_5', 'Time-series 销售预测', 'technical', 'data', 'Chewy', 3, '来源 BurnR2_04（一手抓取 [A]）。（Hard）：分解 trend/seasonality/residual，forecast next quarter。'),
  q('qr204_chewy_6', 'Sales 下降诊断', 'case', 'strategy', 'Chewy', 3, '来源 BurnR2_04（一手抓取 [A]）。（Medium / case）：funnel + cohort + cohort × product_category。'),
  q('qr204_chewy_7', '数据反对公司信仰时怎么办', 'case', 'strategy', 'Chewy', 3, '来源 BurnR2_04（一手抓取 [A]）。（behavioral / case）：讲 evidence level、找第二来源、跟 stakeholder 共同设计验证实验。'),
  q('qr204_chewy_8', '向非技术受众讲复杂数据', 'behavioral', 'communication', 'Chewy', 3, '来源 BurnR2_04（一手抓取 [A]）。（behavioral）。'),
  q('qr204_rapid7_1', 'Identify Top Customers for Rapid7\'s Solutions', 'technical', 'data', 'Rapid7', 3, '来源 BurnR2_04（论坛/聚合转述 [B]）。（DataLemur）—— 找出花最多钱或使用最频繁的 customer，常见模式：top-N per group + spend/scan frequency 复合 ranking。 ｜ 教练建议（M3 生成，未经核实，人名/校友人数一律不要当事实）：Rapid7 对 Northeastern 校友友好，2 个校友在 InsightIDR 团队。**最大短板是安全语感**——Zihao 用 1 小时读 Rapid7 公开 engineering blog（`https://www.rapid7.com/blog/`）就能 cover 50% case。STAR 故事选 schema-bound agent 那段能讲"我懂复杂系统 + 我能让 LLM 可靠输出"——比一般 BART-MNLI 故事更切题。'),
  q('qr204_rapid7_2', 'Window function 计算 scan frequency rolling 7-day', 'technical', 'data', 'Rapid7', 3, '来源 BurnR2_04（论坛/聚合转述 [B]）。`security_scans(customer_id, scan_date, vuln_count)` → 7 天滚动平均。'),
  q('qr204_rapid7_3', 'CASE WHEN + 窗口函数判 customer tier', 'technical', 'data', 'Rapid7', 3, '来源 BurnR2_04（论坛/聚合转述 [B]）。（Medium）：基于 RFM 段定义 VIP，给出"VIP customer engagement" 子群。'),
  q('qr204_rapid7_4', 'Slow distributed query 诊断', 'technical', 'data', 'Rapid7', 3, '来源 BurnR2_04（论坛/聚合转述 [B]）。（架构题）：telemetry log 表，10 亿行 / 月；如何建索引、partition by date、materialize 聚合。'),
  q('qr204_rapid7_5', 'Sudden spike in failed logins', 'case', 'strategy', 'Rapid7', 3, '来源 BurnR2_04（论坛/聚合转述 [B]）。（diagnostic case）：从 geo、user agent、time-of-day、asset criticality 拆解。'),
  q('qr204_rapid7_6', 'InsightVM upsell customer 优先级', 'case', 'strategy', 'Rapid7', 3, '来源 BurnR2_04（论坛/聚合转述 [B]）。（product case）：adoption score = features used / features available，结合 RFM 排 upsell queue。'),
  q('qr204_rapid7_7', '15% 客户活跃度下降诊断', 'case', 'strategy', 'Rapid7', 3, '来源 BurnR2_04（论坛/聚合转述 [B]）。（case）：external (macro/CVE) → product (release incident) → customer (M&A) → 抽样。'),
  q('qr204_rapid7_8', 'STAR 错误处理', 'behavioral', 'communication', 'Rapid7', 3, '来源 BurnR2_04（论坛/聚合转述 [B]）。（behavioral）：跟 stakeholder 提"我们 model 错了"的故事。'),
  q('qr204_flywire_1', 'Monthly Average Transaction Amount by Country', 'technical', 'data', 'Flywire', 3, '来源 BurnR2_04（一手抓取 [A]）。（DataLemur Q1）：`transactions(transaction_id, client_id, transaction_date, country, amount)`。`DATE_TRUNC(\'month\', transaction_date)` + `AVG() OVER (PARTITION BY country, year_month)`，postgres。 ｜ 教练建议（M3 生成，未经核实，人名/校友人数一律不要当事实）：Flywire SQL 题**比 Wayfair/HubSpot 更系统化、更偏 payments**——所以 DataLemur 那 10 题每题都做 3 遍。Zihao 在 Northeastern 学过 FIN/MGT finance 类选修的话，把 FX rate、cross-border settlement、PSP 这三个词加入 vocabulary 即可。'),
  q('qr204_flywire_2', 'Total Received per Client per Month', 'technical', 'data', 'Flywire', 3, '来源 BurnR2_04（一手抓取 [A]）。（DataLemur Q2）：`clients` + `transactions` join，按 receiver_id + month 聚合，descending sort。'),
  q('qr204_flywire_3', 'DISTINCT 去重', 'technical', 'data', 'Flywire', 3, '来源 BurnR2_04（一手抓取 [A]）。（DataLemur Q3）：`SELECT DISTINCT job_title FROM flywire_employees`。'),
  q('qr204_flywire_4', 'Avg Transaction Amount by Currency', 'technical', 'data', 'Flywire', 3, '来源 BurnR2_04（一手抓取 [A]）。（DataLemur Q4）：`EXTRACT(MONTH FROM transaction_date) + currency GROUP BY`。'),
  q('qr204_flywire_5', 'UNION 把 contractors + employees 合表', 'technical', 'data', 'Flywire', 3, '来源 BurnR2_04（一手抓取 [A]）。（DataLemur Q5）。'),
  q('qr204_flywire_6', 'CTR + Conversion Rate for Marketing Campaign', 'technical', 'data', 'Flywire', 3, '来源 BurnR2_04（一手抓取 [A]）。（DataLemur Q6）：`ads(ad_id, user_id, timestamp, clicked)` + `purchases`，计算 CTR + 转化率。'),
  q('qr204_flywire_7', 'API → JSON → DB ETL 自动化', 'technical', 'data', 'Flywire', 3, '来源 BurnR2_04（一手抓取 [A]）。Python `requests` + `json` + `psycopg2` 或 `sqlalchemy` 写一个函数。'),
  q('qr204_flywire_8', 'International payment 失败率突然升高 5pp', 'case', 'strategy', 'Flywire', 3, '来源 BurnR2_04（一手抓取 [A]）。（diagnostic case）：按 corridor、currency、payment_method、PSP、customer segment 拆。'),
  q('qr204_zoominfo_1', 'Top 3 customers by region with ties', 'technical', 'data', 'ZoomInfo', 3, '来源 BurnR2_04（一手抓取 [A]）。`RANK() OVER (PARTITION BY region ORDER BY spend DESC)`，ties 用 `DENSE_RANK` 处理。 ｜ 教练建议（M3 生成，未经核实，人名/校友人数一律不要当事实）：ZoomInfo DA 题里 Python 比例比别家高 30%——Zihao 把 list comprehension、pandas groupby、API request 3 块再练一次。**注意 visa**：Waltham office 大部分是 H-1B 友好，但 Vancouver WA office 走 GC 友好；OPT + STEM extension 可用，但 H-1B 抽签有运气成分。'),
  q('qr204_zoominfo_2', 'LEFT JOIN vs FULL OUTER JOIN 场景', 'technical', 'data', 'ZoomInfo', 3, '来源 BurnR2_04（一手抓取 [A]）。LEFT = 保留左表主键；FULL = 保留双侧，对账场景。'),
  q('qr204_zoominfo_3', 'Optimize slow multi-join query', 'technical', 'data', 'ZoomInfo', 3, '来源 BurnR2_04（一手抓取 [A]）。（Hard）。'),
  q('qr204_zoominfo_4', 'Window running total 30-day sign-ups', 'technical', 'data', 'ZoomInfo', 3, '来源 BurnR2_04（一手抓取 [A]）。`SUM() OVER (ORDER BY date ROWS BETWEEN 29 PRECEDING AND CURRENT ROW)`。'),
  q('qr204_zoominfo_5', '处理 join 时 duplicate', 'technical', 'data', 'ZoomInfo', 3, '来源 BurnR2_04（一手抓取 [A]）。ROW_NUMBER 去重 + check 业务键。'),
  q('qr204_zoominfo_6', 'Python: API → JSON → DB 自动化', 'technical', 'data', 'ZoomInfo', 3, '来源 BurnR2_04（一手抓取 [A]）。。'),
  q('qr204_zoominfo_7', 'Python: missing values + anomalies in daily CSV', 'technical', 'data', 'ZoomInfo', 3, '来源 BurnR2_04（一手抓取 [A]）。`pandas.isnull()`、`zscore`、IQR。'),
  q('qr204_zoominfo_8', 'Python: sequence generation function', 'technical', 'data', 'ZoomInfo', 3, '来源 BurnR2_04（一手抓取 [A]）。（算法热身题）。'),
  q('qr204_iterable_1', 'Conflicting data sources 怎么办', 'behavioral', 'communication', 'Iterable', 3, '来源 BurnR2_04（一手抓取 [A]）。（behavioral + technical）：找 gold source、reconciliation、data contract。 ｜ 教练建议（M3 生成，未经核实，人名/校友人数一律不要当事实）：**Iterable 是 12 家里"对 Zihao 性格最 match"的**——文化开放、强调双向沟通、SQL 难度不极端。准备 2 份 strong 故事：① schema-bound agent（讲 reliability、constraints、production-readiness），② 一个影响 stakeholder 的 STAR。**注意 visa**：SF 办公室对 H-1B 友好度中等，OPT 可用但 sponsor 走 case-by-case。'),
  q('qr204_iterable_2', '从 0 搭 dashboard — 选什么 metrics', 'case', 'strategy', 'Iterable', 3, '来源 BurnR2_04（一手抓取 [A]）。（product case）：Iterable 客户的 send volume、open rate、CTR、unsubscribe、reactivation。'),
  q('qr204_iterable_3', 'Data integrity 大型 messy dataset', 'technical', 'data', 'Iterable', 3, '来源 BurnR2_04（一手抓取 [A]）。（process）：quality check、unit test、监控。'),
  q('qr204_iterable_4', '描述一个 complex SQL query 解决业务问题', 'technical', 'data', 'Iterable', 3, '来源 BurnR2_04（一手抓取 [A]）。（behavioral / technical）。'),
  q('qr204_iterable_5', '数据 incomplete 时如何接 request', 'behavioral', 'communication', 'Iterable', 3, '来源 BurnR2_04（一手抓取 [A]）。（behavioral + technical）。'),
  q('qr204_iterable_6', '用数据影响 stakeholder', 'behavioral', 'communication', 'Iterable', 3, '来源 BurnR2_04（一手抓取 [A]）。（behavioral）。'),
  q('qr204_iterable_7', '接收 feedback on analysis 怎么处理', 'behavioral', 'communication', 'Iterable', 3, '来源 BurnR2_04（一手抓取 [A]）。（behavioral）。'),
  q('qr204_iterable_8', 'Calculate Monthly Sales Growth by Product Category', 'technical', 'data', 'Iterable', 3, '来源 BurnR2_04（一手抓取 [A]）。（Medium SQL）：`JOINs + window functions`，`LAG(monthly_sales) OVER (PARTITION BY cat ORDER BY month)`。'),
  q('qr204_starburst_1', 'Investigate slow distributed query', 'technical', 'data', 'Starburst Data', 3, '来源 BurnR2_04（论坛/聚合转述 [B]）。（Hard）：trino EXPLAIN 看 stage、看 broadcast/shuffle join、数据 skew、partition pruning。 ｜ 教练建议（M3 生成，未经核实，人名/校友人数一律不要当事实）：**Zihao 投 Starburst 主要是练手**——这家 DA 招聘量小、偏 data engineering、面试偏 distributed systems 知识。但它是 trino 的母公司，把 Starburst Academy 课程刷完一遍，分布式 SQL 知识直接跨越到 12 家其它公司面试都能用——投入产出比很高。'),
  q('qr204_starburst_2', 'Window function on telemetry log', 'technical', 'data', 'Starburst Data', 3, '来源 BurnR2_04（论坛/聚合转述 [B]）。ROW_NUMBER/RANK + 30-day rolling，PB 级。'),
  q('qr204_starburst_3', 'Unnest arrays/structs in JSON log', 'technical', 'data', 'Starburst Data', 3, '来源 BurnR2_04（论坛/聚合转述 [B]）。Trino 语法 `CROSS JOIN UNNEST(...)`。'),
  q('qr204_starburst_4', '诊断 multi-tenant warehouse latency spike', 'case', 'strategy', 'Starburst Data', 3, '来源 BurnR2_04（论坛/聚合转述 [B]）。（case）：resource groups、heavy scan、predicate pushdown、cache hit rate。'),
  q('qr204_starburst_5', '设计 star/snowflake schema for a 业务需求', 'case', 'strategy', 'Starburst Data', 3, '来源 BurnR2_04（论坛/聚合转述 [B]）。（modeling case）。'),
  q('qr204_starburst_6', 'Iceberg vs Delta Lake vs Hive 选型', 'technical', 'data', 'Starburst Data', 3, '来源 BurnR2_04（论坛/聚合转述 [B]）。（architecture knowledge）。'),
  q('qr204_starburst_7', 'Open-ended 5-min walkthrough of past project', 'technical', 'data', 'Starburst Data', 3, '来源 BurnR2_04（论坛/聚合转述 [B]）。（presentation）。'),
  q('qr204_starburst_8', 'starburst SQL 文档 deep-dive', 'technical', 'data', 'Starburst Data', 3, '来源 BurnR2_04（论坛/聚合转述 [B]）。—— 官方培训视频（Starburst Academy 公开免费）是必看。'),
  q('qr204_snyk_1', 'Missing values / inconsistencies 处理', 'technical', 'data', 'Snyk', 3, '来源 BurnR2_04（一手抓取 [A]）。。 ｜ 教练建议（M3 生成，未经核实，人名/校友人数一律不要当事实）：**Snyk 是 12 家里 schema-bound agent 故事最 match 的**——Snyk 的产品就是"约束 + 验证"（scan rules + policy），跟 Zihao 的 schema-bound agent 项目哲学完全同源。准备 1 段 "I built an agent that constrains LLM output via JSON schema, achieving 99.x% reliability" STAR，可以直接套 Snyk 的 culture questions。**注意 visa**：Remote / Boston 都行；Snyk 在 OPT extension 阶段 sponsor 历史稳定。'),
  q('qr204_snyk_2', '描述一个 complex data project + tools', 'behavioral', 'communication', 'Snyk', 3, '来源 BurnR2_04（一手抓取 [A]）。（behavioral + technical）。'),
  q('qr204_snyk_3', 'Scrape + structure a web data source', 'technical', 'data', 'Snyk', 3, '来源 BurnR2_04（一手抓取 [A]）。`requests` + `BeautifulSoup` / `Playwright` + schema 设计。'),
  q('qr204_snyk_4', 'Scripting for data automation', 'technical', 'data', 'Snyk', 3, '来源 BurnR2_04（一手抓取 [A]）。`cron` + `pytest`。'),
  q('qr204_snyk_5', '确保 analytical model accuracy + integrity', 'technical', 'data', 'Snyk', 3, '来源 BurnR2_04（一手抓取 [A]）。（process）。'),
  q('qr204_snyk_6', '向非技术 stakeholder 讲技术发现', 'behavioral', 'communication', 'Snyk', 3, '来源 BurnR2_04（一手抓取 [A]）。（behavioral）。'),
  q('qr204_snyk_7', 'Project obstacle 如何克服', 'behavioral', 'communication', 'Snyk', 3, '来源 BurnR2_04（一手抓取 [A]）。（behavioral）。'),
  q('qr204_snyk_8', '为什么 developer security？', 'behavioral', 'communication', 'Snyk', 3, '来源 BurnR2_04（一手抓取 [A]）。（motivation / culture fit）。'),
];

export const batch2QuestionMeta = {
  generatedAt: NOW,
  total: 95,
  companies: 12,
  source: 'BurnR2_04_Interview_Intel_Batch2_2026-08-09.md',
};
