// AUTO-GENERATED from "M3 Research Burn/BurnZ04_Outreach_EmailTemplates_47_2026-08-10.md".
// 47 outreach templates parsed out of the burn-z04 research run (the source report's
// 48th template, L3, was truncated by the generating run's output limit and is excluded).
//
// Provenance of the underlying advice: 9 successful web_fetch calls against Hunter.io's
// cold-email research, Salesforce's cold-email template post, Workable, and Wikipedia.
// The report's own web_search calls all timed out, so reply-rate figures are the cited
// vendors' published numbers, NOT measured results for this job search. They are stored
// as tags, not as promises.
//
// One repair applied during generation: four source templates nested a {{field}} inside
// an outer placeholder's e.g. example and closed the outer one with a single "}", which
// renders as a broken merge field. Those are re-closed with "}}"; verify-templates.mjs
// asserts brace balance so the defect cannot come back silently.
//
// NO real third-party email address appears here — every recipient value is a
// {{merge_field}}. Do not substitute guessed first.last@company.com addresses.
// Do not hand-edit; regenerate from the source report.
import type { EmailTemplate } from './types';

const NOW = '2026-08-10T05:00:00.000Z';

const t = (
  id: string, name: string, category: EmailTemplate['category'], subject: string,
  body: string, mergeFields: string[], tags: string[], scenario: string,
): EmailTemplate => ({
  id, name, category, subject, body, mergeFields, tags, scenario,
  useCount: 0, createdAt: NOW, updatedAt: NOW,
});

export const outreachTemplates: EmailTemplate[] = [
  t("z04-a1", "A1 · 投递后无回应 → 直接 cold 给招聘官（标准版）", "cold_outreach", "{{first_name}} — quick question on the {{role}} pipeline", "Hi {{first_name}},\n\nI applied for the {{role}} position at {{company}} on {{application_date}}, and I wanted to follow up directly rather than sit in the queue.\n\nA quick snapshot so you can decide in 30 seconds: I'm a {{graduation_month}} {{graduation_year}} MS Analytics candidate at Northeastern University, focused on {{specialty}}. My most relevant work includes {{1_line_project_or_outcome, e.g., \"a churn model that re-segmented 240k customers and lifted retention +6%\"}}.\n\nI noticed your team has been hiring across {{team_or_function}}, so I'm open to either this posted role or adjacent ones you might be staffing up for in {{target_start_window}}.\n\nWould it help if I sent over a 1-page project summary or applied to a different req? Happy to work with your process either way.\n\nBest,\n{{your_name}}\n{{your_phone}} · {{your_linkedin_url}}", ["1_line_project_or_outcome", "application_date", "company", "first_name", "graduation_month", "graduation_year", "role", "specialty", "target_start_window", "team_or_function", "your_linkedin_url", "your_name", "your_phone"], ["Recruiter / TA cold", "rate: Hunter 数据：cold email 平均回复率 3.3%，但 Hunter State of Email Outreach 2026 显示 3 封序列可达 6.8%（https://hunter.io/blog/received-no"], "在 LinkedIn 上看到该公司 in-house recruiter，明确该公司正在招相关岗位，但简历库显示 application status 长时间为 \"In Review\"。\n\n注意事项：\n- 千万别猜招聘官邮箱 —— 在 LinkedIn 搜 \"{{company}} recruiter\" / \"{{company}} talent acquisition\"，官方公开邮箱常是 `talent@{{company_domain}}` 或 `careers@{{company_domain}}`。可以先用 Hunter.io Domain Search（公开网页）查 \"{{company_domain}}\" 公开邮箱格式作为线索。\n- 第三方 agency recruiter 可以直接 cold；in-house recruiter 务必确认岗位真的 active（看 LinkedIn job posting 日期）。\n- Salesforce 经验：ratio of \"I/my\" to \"you/your\" 保持 1:2 — 我已经在上面的版本里控制了。"),
  t("z04-a2", "A2 · 招聘官在 LinkedIn 主动联系过你 → 2 周后回温", "cold_outreach", "Still interested in {{role}} at {{company}}?", "Hi {{first_name}},\n\nCircling back on the {{role}} role we chatted about on {{date_of_last_conversation}}. I know reqs shift, so here's a 20-second update rather than a re-pitch:\n\n- {{new_credential_1, e.g., \"finished the SQL + dbt track on my NEU co-op\"}}\n- {{new_credential_2, e.g., \"wrapped the capstone project with {{client_or_partner}}\"}}\n- Still targeting a {{start_window}} start and based in {{city_or_remote_preference}}\n\nIf {{role}} has closed or paused, no problem — if there's an adjacent opening on {{team_or_function}}, I'd love to be considered. If the timing is genuinely off, \"not now\" is also a useful reply.\n\nThanks,\n{{your_name}}\n{{your_phone}} · {{your_linkedin_url}}", ["city_or_remote_preference", "client_or_partner", "date_of_last_conversation", "first_name", "new_credential_1", "new_credential_2", "role", "start_window", "team_or_function", "your_linkedin_url", "your_name", "your_phone"], ["Recruiter / TA cold", "rate: Hunter 跟进 #1 通常达到回复峰值（\"reply rate usually peaks at follow-up #1 or #2, then decays sharply\" — https://hunter.io/blog/the"], "Recruiter InMailed 你 2-3 周前，你回了第一封但没再跟进；现在他要 close 这个 req 或你希望回到 active pipeline。\n\n注意事项：\n- 这是 Hunter \"rejection-then-retreat\"（Cialdini 的 door-in-the-face）的反向应用 — 把\"小请求\"放最后，给对方清晰的退出选项。\n- 用具体时间锚（\"we chatted on {{date}}\"）让 recruiter 不用回查就能想起你。\n- 千万别写\"hope this finds you well\"或\"just checking in\" — Hunter 数据 70% cold email 不被跟进、跟进用\"just checking in\"被广泛报告为低质信号。"),
  t("z04-a3", "A3 · Agency recruiter（第三方）cold — 主动出击", "cold_outreach", "{{specialty}} candidate, NEU Dec '26 — open to intro?", "Hi {{first_name}},\n\nI see you focus on {{specialty_or_function}} placements — wanted to put myself on your radar before you need to fill a role.\n\nSnapshot:\n- {{graduation_month}} {{graduation_year}} MS Analytics, Northeastern University (Khoury College)\n- Track record: {{one_quantified_outcome, e.g., \"built a forecasting model that cut forecast error from 18% to 9% on a $4M inventory\"}}\n- Targeting: {{role_type_1}} / {{role_type_2}} in {{target_cities_or_remote}} starting {{start_window}}\n- {{sponsorship_note, e.g., \"Authorized to work in the US long-term\"}}\n\nIf you're staffing for a {{specific_role_you_saw}}, I'd love a 15-minute screen. If not now, can I ask you to keep me in mind and I'll check back in {{check_back_window, e.g., \"Q1 2027\"}}?\n\nThanks,\n{{your_name}}\n{{resume_pdf_link, attach only after reply per Hunter's deliverability guidance}}", ["check_back_window", "first_name", "graduation_month", "graduation_year", "one_quantified_outcome", "resume_pdf_link", "role_type_1", "role_type_2", "specialty_or_function", "specific_role_you_saw", "sponsorship_note", "start_window", "target_cities_or_remote", "your_name"], ["Recruiter / TA cold", "rate: 8-12%（Hunter: \"personalized subject lines boost open rates by 50%\"；带量化结果的外联 AeroChat 案例达到 40% reply，https://hunter.io/bl"], "LinkedIn 上发现 agency recruiter 专注 placement 你目标岗位；你想先发制人注册进他的小众人才库。\n\n注意事项：\n- **不要**猜 agency recruiter 个人邮箱 — 用 LinkedIn 上他们的官方 contact 链接 / 公司邮箱（一般是 `firstname@{{agency_domain}}`，但**只在确认后**用）。\n- Salesforce 经验：\"Referral from a mutual connection\" 和 \"Not sure who to contact\" 模板都强调 — 千万别写\"sent to 10,000 other people\"那种通用垃圾。\n- 关于 attachment：Hunter 数据（https://hunter.io/blog/16-questions-and-answers-about-how-to-write-outreach-emails-that-get-replies.md）显示初始邮件含超链接/附件会被 spam filter 拉黑 — 把 resume 留到对方回信后再发。"),
  t("z04-a4", "A4 · Recruiter re-engage — 拒绝后 6 个月回温", "cold_outreach", "Update: still interested in {{target_function}} roles", "Hi {{first_name}},\n\nYou and I spoke in {{month_year_of_last_conversation}} about {{role_or_track}} at {{company}}. At the time, the team was looking for {{reason_for_old_no}} and I wasn't the right fit.\n\nA few things have changed on my side since then:\n- {{credential_1, e.g., \"completed a 6-month co-op as an analytics engineer at {{company_2}}\"}}\n- {{credential_2, e.g., \"added {{skill_or_credential}} to my stack\"}}\n- Targeting {{start_window}} start in {{city_or_remote_preference}}\n\nIf the {{function}} market has loosened up on your desk, would it be worth a 15-minute re-intro? Either way, thank you — your feedback in {{month_year}} shaped how I approached the next {{time_window, e.g., \"9 months\"}}.\n\nBest,\n{{your_name}}\n{{your_phone}} · {{your_linkedin_url}}", ["city_or_remote_preference", "company", "company_2", "credential_1", "credential_2", "first_name", "function", "month_year", "month_year_of_last_conversation", "reason_for_old_no", "role_or_track", "skill_or_credential", "start_window", "time_window", "your_linkedin_url", "your_name", "your_phone"], ["Recruiter / TA cold", "rate: 12-20%（warm re-engagement 历史经验；新 credential 加持 Hunter \"give-first\" 数据：3-5× reply lift）"], "6-12 个月前被某 recruiter reject，对方在 LinkedIn 上又活跃了；你想换 timeline 重新进 pipeline。\n\n注意事项：\n- 这是 Hunter \"the giver-first\" 心理战术（https://hunter.io/blog/3-psychology-backed-ways-to-get-more-email-replies-in-2026.md）：先承认 old feedback 的价值，建立 reciprocity。\n- Salesforce 经验：\"If you're not sure who to contact\" 模板建议 — 如果你不确定 recruiter 是不是还在 active，先 InMail 一句话确认：\"still with {{company}}?\"，然后再发完整邮件。"),
  t("z04-a5", "A5 · 给 Talent Sourcer 的 niche pitch（主动投递前先注册）", "cold_outreach", "Sourcing intel — {{your_specialty}} for {{team}} at {{company}}", "Hi {{first_name}},\n\nReading your recent LinkedIn activity, I think {{company}} is roughly {{time_horizon, e.g., \"two quarters\"}} away from needing an analytics profile like mine. Rather than wait for the req to post, here's a 30-second pitch so you're not starting from zero when it opens.\n\nWhy I'm worth a quick look:\n- {{graduation_month}} {{graduation_year}} MS Analytics, Northeastern (Khoury)\n- Specialize in {{specialty, e.g., \"experimentation, causal inference, and SQL/dbt\"}}\n- Last {{time_window}} = {{one_quantified_outcome, e.g., \"owned end-to-end A/B testing for {{client_or_product}} that lifted conversion +4.1%\"}}\n- {{sponsorship_note, e.g., \"US work authorization, no sponsorship needed now\"}}\n\nOpen question: am I reading the {{company}} roadmap right, or am I missing the team that's most likely to hire this profile? Even a one-line steer (\"talk to {{team}} instead\") would be helpful.\n\nThanks for reading,\n{{your_name}}\n{{your_phone}} · {{your_linkedin_url}}", ["client_or_product", "company", "first_name", "graduation_month", "graduation_year", "one_quantified_outcome", "specialty", "sponsorship_note", "team", "time_horizon", "time_window", "your_linkedin_url", "your_name", "your_phone"], ["Recruiter / TA cold", "rate: 6-10%（Sourcer 经常 deal flow-driven，看到 niche resume 会留档）；带 calibrated question 的版本（Hunter 2026 anti-cold emailer — \"credib"], "公司未公开招你目标岗位，但你查 LinkedIn / Crunchbase 推断他们大概率会招；先在 sourcer 那里留简历。\n\n注意事项：\n- 这套用了 Hunter \"single-question diagnostic\" + \"permission-based CTA\" — 用一句 \"am I reading this right?\" 降低对方回复门槛。\n- 关于邮箱：`firstname@{{company_domain}}` 是常见的公开格式猜测；**严格用 Hunter.io Domain Search 或 LinkedIn Recruiter 个人页面**确认后再发，不要发信到 `info@`、`careers@` 这类 generic inbox。"),
  t("z04-b1", "B1 · 通过 LinkedIn / job board 找到 HM 的标准 cold", "cold_outreach", "{{your_specialty}} for {{team}} at {{company}}", "Hi {{first_name}},\n\nI read {{specific_public_artifact, e.g., \"your talk at {{conference}} / your interview on {{podcast}} / your team's blog post on {{topic}}\"}} — the point about {{specific_point_you_resonated_with}} matches a problem I worked on at {{previous_context}}.\n\nSnapshot:\n- {{graduation_month}} {{graduation_year}} MS Analytics, Northeastern (Khoury)\n- {{one_quantified_outcome, e.g., \"designed a churn-propensity model that re-targeted 240k users and reduced churn -3.8%\"}}\n- Tools I default to: {{tool_1}}, {{tool_2}}, {{tool_3}}\n- Targeting: full-time {{role_type}} on {{team}} or adjacent, {{start_window}} start\n\nI don't want to take a meeting just to introduce myself. If {{team}} is hiring for {{role_type}} in the next two quarters, would it help if I sent a 1-page write-up of how I'd approach {{specific_problem_you_observed}} in your org? Or, if the timing is wrong, \"not hiring yet\" is the most useful answer you can give me.\n\nThanks for the read,\n{{your_name}}\n{{your_phone}} · {{your_linkedin_url}}", ["conference", "first_name", "graduation_month", "graduation_year", "one_quantified_outcome", "podcast", "previous_context", "role_type", "specific_point_you_resonated_with", "specific_problem_you_observed", "specific_public_artifact", "start_window", "team", "tool_1", "tool_2", "tool_3", "topic", "your_linkedin_url", "your_name", "your_phone"], ["Hiring manager cold", "rate: 5-10%（highly personalized, mention public artifact）；Kovasys 经验：保持 1 封 + 2 封跟进 + 纯文本 + 无链接 = 高 reply（https://hunter.io/bl"], "LinkedIn 上找到 HM（VP of Analytics、Director of Data Science、Head of Growth），他在 hire 自己的 +1/+2；你想绕开 ATS black hole。\n\n注意事项：\n- **不要**直接 cold HM 给 full pitch — Hunter \"anti-cold emailer\" 数据显示 65% 决策者抱怨 \"too sales-focused\"。Permission CTA（\"would it help if I sent...\"）回退经验值最高。\n- 关于数据：Hunter 数据 67% 决策者更可能回复提到 public information 的邮件（https://hunter.io/blog/16-questions-and-answers-about-how-to-write-outreach-emails-that-get-replies.md）—— 你提到 HM 公开内容一定要真实可点击。\n- HTML 用 plain text（Hunter：HTML 反弹 +674%）。"),
  t("z04-b2", "B2 · 通过校友 / 同事 connection 引荐后的开场", "cold_outreach", "{{alum_first_name}} mentioned I should reach out — about {{team}}", "Hi {{first_name}},\n\n{{alum_first_name}} ({{alum_role}} at {{alum_company}}) and I were catching up at {{context, e.g., \"a Khoury alumni event / over coffee last week\"}} and mentioned I'm looking at {{team}}-type roles. They suggested I send you a quick note given how aligned your work is with my background.\n\nBackground in one paragraph:\n- {{graduation_month}} {{graduation_year}} MS Analytics, Northeastern\n- Recent work: {{one_quantified_outcome, e.g., \"built a propensity model that improved retention +6% on a 240k-user cohort\"}}\n- Why {{company}}: {{one_specific_reason, e.g., \"your team's published approach to {{topic}} lines up with how I want to grow\"}}\n\nI'll keep this short — if {{team}} is hiring for {{role_type}} in the {{time_window}}, would a 20-minute intro make sense? And if the timing is genuinely off, an honest \"come back in {{check_back_window}}\" is the most useful reply.\n\nThanks,\n{{your_name}}\n{{your_phone}} · {{your_linkedin_url}}", ["alum_company", "alum_first_name", "alum_role", "check_back_window", "company", "context", "first_name", "graduation_month", "graduation_year", "one_quantified_outcome", "one_specific_reason", "role_type", "team", "time_window", "topic", "your_linkedin_url", "your_name", "your_phone"], ["Hiring manager cold", "rate: 15-25%（referral 是 cold outreach 中回复率最高的类型之一；Salesforce 17 个模板中把 referral 放第一位就因为这个）"], "LinkedIn / NEU alumni network 上发现校友在目标 HM 团队；校友同意口头 mention 你，你写 follow-up。\n\n注意事项：\n- 引用校友的话必须在**经过对方许可后**写 — Salesforce 的 \"Referral from a mutual connection\" 模板的整个逻辑就是：感谢 → ask for intro。Hunter \"anti-cold emailer\" 提醒：\"fake name-drop\" 是 2026 年最被讨厌的骗术之一（https://hunter.io/blog/the-2026-anti-cold-emailer-mentality.md）。\n- 校友 contact 信息用 **HuskyCareer Network / LinkedIn Alumni Tool \"Find Alumni\"** 找——这是 NEU 官方提供的合规校友触达入口（careers.northeastern.edu）。**不要**写 `firstname.lastname@{{company_domain}}` 的猜测地址。"),
  t("z04-b3", "B3 · HM 在某活动 / podcast / article 提过你关心的方向", "cold_outreach", "Re: your {{artifact_type}} on {{topic}}", "Hi {{first_name}},\n\nYour {{artifact_type}} on {{topic}} (link: {{public_link}}) made me rethink how I'm approaching {{my_current_challenge, e.g., \"my capstone on churn modeling\"}}. Specifically, your line about {{specific_quote_or_idea}} is the angle I hadn't seen written down anywhere.\n\nBackground so you don't have to look me up cold:\n- {{graduation_month}} {{graduation_year}} MS Analytics, Northeastern\n- {{one_quantified_outcome}}\n- I write / build / speak about {{adjacent_topic, e.g., \"experimentation design and causal inference in B2B SaaS\"}}\n\nTwo questions if you have a minute:\n1. Is {{team}} still building in {{adjacent_area}}, and would an analyst / associate who thinks about {{specific_concept}} from your {{artifact_type}} be useful?\n2. If not a fit today, who's the best person on {{team}} to talk to about {{specific_concept}}?\n\nNo need for a long reply — even a one-line steer (\"talk to {{name}}\" or \"come back {{time_window}}\") is helpful.\n\nThanks,\n{{your_name}}\n{{your_phone}} · {{your_linkedin_url}}", ["adjacent_area", "adjacent_topic", "artifact_type", "first_name", "graduation_month", "graduation_year", "my_current_challenge", "name", "one_quantified_outcome", "public_link", "specific_concept", "specific_quote_or_idea", "team", "time_window", "topic", "your_linkedin_url", "your_name", "your_phone"], ["Hiring manager cold", "rate: 8-15%（Hunter: personalization based on public info → 67% more likely to reply, https://hunter.io/blog/ab-testing-your-em"], "HM 最近 published something（blog post / conference talk / interview）正好对你技术栈 & 业务领域；用此作为钩子。\n\n注意事项：\n- Salesforce 经验：\"Recent event outreach\" 和 \"Making connections\" 模板的核心 — 用具体公开信息作为钩子。Hunter 数据：含具体 hook 的邮件回复率 6-12%。\n- 引用 HM 公开言论必须**真实存在**，否则就违反 Hunter 的 \"fake name-drop\" 红线。"),
  t("z04-b4", "B4 · 给 HM 的 \"permission to close your file?\"（breakup email 的反向应用）", "cold_outreach", "Closing my file — last note from {{your_name}}", "Hi {{first_name}},\n\nI've reached out twice about {{role_type}} opportunities on {{team}} without hearing back, and I want to respect your inbox. Before I close this thread, one quick check:\n\nIs the lack of reply because (a) no relevant role is open right now, (b) timing is off and I should reconnect in {{time_window, e.g., \"Q2 2027\"}}, or (c) I've been sending to the wrong person and you can point me to the right colleague?\n\nAny of those is a useful answer. If you don't have a minute to reply, I'll mark your file as \"closed — reconnect {{time_window}}\" on my end and won't keep pinging.\n\nThanks for the consideration,\n{{your_name}}\n{{your_phone}} · {{your_linkedin_url}}", ["first_name", "role_type", "team", "time_window", "your_linkedin_url", "your_name", "your_phone"], ["Hiring manager cold", "rate: 10-18%（最后的\"软退出\"邮件历史经验值高；很多被忽略的 cold 最终是 dev / timing 问题，对方其实有意愿）"], "你已经给 HM 发过 2-3 封 cold，无回复；用\"我准备关闭我的档案\"做最后一击（Hunter 2026 anti-cold emailer 警告\"breakup email\" 也是骗术之一，所以这是**真实** breakpoint，不是 dramatic 戏）。\n\n注意事项：\n- 这跟 Hunter 的 rejection-then-retreat 一致（https://hunter.io/blog/rejection-then-retreat.md）：把请求主动降级到最低 friction —— 单选问题，10 秒回复。\n- 注意区别于 dramatic breakup email（\"Should I close your file? Last try!\"）。**不要**用制造压力的话术（Hunter \"fake urgency\" 红线）。"),
  t("z04-b5", "B5 · 给 HM 的 multi-stakeholder 邮件（让 HM 转发给团队）", "cold_outreach", "Worth forwarding? {{role_type}} candidate, {{team}}", "Hi {{first_name}},\n\nI'm reaching out because {{company}}'s {{team}} function is on my short list for {{role_type}} roles. If {{team}} is in your reporting line or you sit close to it, would you be willing to forward this note to the hiring manager, or, if it's easier, point me to the right name?\n\nOne paragraph on me for the forward:\n- {{graduation_month}} {{graduation_year}} MS Analytics, Northeastern\n- {{one_quantified_outcome}}\n- Open to {{start_window}} start, {{city_or_remote_preference}}\n\nIf you'd rather I cold-message the HM directly, no offense taken — just tell me the role number or the name and I'll go through the proper channel.\n\nThanks,\n{{your_name}}\n{{your_phone}} · {{your_linkedin_url}}", ["city_or_remote_preference", "company", "first_name", "graduation_month", "graduation_year", "one_quantified_outcome", "role_type", "start_window", "team", "your_linkedin_url", "your_name", "your_phone"], ["Hiring manager cold", "rate: 12-22%（internal router 类请求回复率非常高 — 对方可能也是曾经在类似位置被 help 的人）"], "HM 是 decision-maker 但不是 manager；如果 HM 自己不在场，安排下属或同事先 connect 你，他/她便于内部转发。\n\n注意事项：\n- 这跟 Salesforce \"Not sure who to contact\" 模板完全一致 — 用一句话降低对方帮你 router 的成本。\n- Hunter \"nuisance test\" 自检：是否对收件人有 value？如果你请求 forwarding 还要对方花 30 秒看简历附件，价值太低 — 让对方可以纯文本 forward。"),
  t("z04-c1", "C1 · 给 NEU 校友 — 第一次 cold，请 15 分钟 coffee chat", "referral_request", "NEU '26 Analytics — quick question for a {{target_function}} alum", "Hi {{alum_first_name}},\n\nFellow Husky here — I'm {{your_name}}, MS Analytics '26 at Khoury, specializing in {{specialty}}. Saw you're at {{alum_company}} doing {{alum_role_function}} and thought it would be more useful to ask a real Husky than another stranger on LinkedIn.\n\nTwo questions I keep getting from my classmates, and I figured you'd have the clearest answers:\n1. What's the realistic {{team_or_function}} entry path at {{alum_company}} for someone with {{your_profile_short}}?\n2. Are there specific teams/projects at {{alum_company}} that hire {{target_role_type}} from MS Analytics backgrounds that I should be tracking?\n\nA 15-minute coffee chat (virtual is fine) in {{time_window}} would be hugely appreciated. If you're slammed, even a 3-sentence email response gets me 80% of the way there.\n\nThanks for considering,\n{{your_name}}\nNEU MS Analytics '26 · {{your_linkedin_url}}", ["alum_company", "alum_first_name", "alum_role_function", "specialty", "target_role_type", "team_or_function", "time_window", "your_linkedin_url", "your_name", "your_profile_short"], ["NEU alumni referral", "rate: 25-40%（同校 alumni connection 历史上是 cold outreach 最高 reply rate 的类目之一；NEU 校友文化相对 strong）"], "HuskyCareer Network 找到 NEU 校友在某 target company 工作；写 cold ask for informational chat。\n\n注意事项：\n- 用 **HuskyCareer Network**（NEU 官方校友目录，careers.northeastern.edu 提供入口）找校友的合规 LinkedIn / 工作邮箱路径。\n- 明确说\"fellow Husky\"在第一行建立 trust anchor（Hunter \"credibility in the first line\" 原则）。"),
  t("z04-c2", "C2 · 给校友 — coffee chat 后 → 问能不能 internal referral", "referral_request", "Thanks for the chat — one small ask", "Hi {{alum_first_name}},\n\nThanks again for the {{chat_date}} chat — your point about {{specific_advice_you_gave}} has already changed how I'm approaching my {{specific_application, e.g., \"{{company}} {{role}} application\"}}.\n\nYou mentioned that {{alum_company}} has an internal referral program. I wanted to ask, on a separate note: would you be comfortable submitting a referral for {{target_role_id_or_title}} on {{team}}? I've attached the role link here for context: {{job_posting_url}}.\n\nTwo things to make this easy for you:\n1. The role is a strong match ({{1_2_line_pitch, e.g., \"analytics on the growth team, which mirrors the work you described\"}}), so the referral wouldn't feel like a stretch.\n2. If you would rather stay out of it, \"happy to refer you informally but prefer to keep my referrals internal to my own team\" is a totally fine answer and I won't push.\n\nThanks,\n{{your_name}}\n{{your_linkedin_url}}", ["1_2_line_pitch", "alum_company", "alum_first_name", "chat_date", "company", "job_posting_url", "role", "specific_advice_you_gave", "specific_application", "target_role_id_or_title", "team", "your_linkedin_url", "your_name"], ["NEU alumni referral", "rate: 35-55%（warm ask after coffee chat 是 golden window；NEU 校友内部 referral 经常 strong）"], "你和校友 coffee chat 已经结束，对方友好；你想 ask 是否愿意做 internal referral。\n\n注意事项：\n- 这是 Hunter \"give-first\" 心理战术的延伸 — 先认可对方价值，再说 ask。\n- **很多公司 referral 政策要求 referrer 在同一个 org / 团队**。Salesforce \"Recent event outreach\" 模板也强调要给 referrer 具体的 role / team 链接，不是空泛 ask。"),
  t("z04-c3", "C3 · 给 NEU 校友 — strong tie, 直接 ask referral（不绕弯）", "referral_request", "Referral ask — {{role}} at {{company}}", "Hey {{alum_first_name}},\n\nI'm formally asking: would you be willing to refer me for the {{role}} opening at {{company}} ({{job_posting_url}})?\n\nYou already know my background, but for the referral form:\n- NEU MS Analytics '26, specializing in {{specialty}}\n- {{one_quantified_outcome}}\n- {{sponsorship_note}}\n\nIf you'd rather not — totally fine, no hard feelings. If you would, the internal ATS portal usually asks for a 2-3 sentence rationale; I'll send that to you pre-filled so all you have to do is paste it in.\n\nDeadline: {{application_deadline_if_any, else \"open until filled\"}}.\n\nEither way, thanks,\n{{your_name}}", ["alum_first_name", "application_deadline_if_any", "company", "job_posting_url", "one_quantified_outcome", "role", "specialty", "sponsorship_note", "your_name"], ["NEU alumni referral", "rate: 50-70%（strong tie + 低 friction + 提供 rationale draft）"], "你和校友已经是 NEU 时期朋友，对方 senior 在你 target company；可以 straightforward ask。\n\n注意事项：\n- \"Strong tie\" 关系下 direct ask 反而最高效。Hunter \"anti-cold emailer\" 提醒：避免 fake familiarity；但这条是 real tie，direct ask 是 OK 的。\n- 提前**准备好 pre-filled referral rationale**，减轻 referrer 负担（Kovasys 经验：把 follow-up 缩短到 3-5 句最能 maintain reply rate，https://hunter.io/blog/customers/it-recruitment-company-saves-30-hours-a-week-prospecting.md）"),
  t("z04-c4", "C4 · 给校友 — 校友已经 refer 但你未被推进 → 跟进", "referral_request", "Following up on your referral — any update?", "Hi {{alum_first_name}},\n\nYou put in a referral for me on {{referral_date}} for the {{role}} role on {{team}} at {{company}}. I haven't heard back, and I'm not sure whether:\n(a) the HM hasn't looked at the referral queue yet,\n(b) the req has been put on hold,\n(c) the role was filled internally, or\n(d) something else entirely.\n\nWould you be willing to ping {{hm_name_or_team, if_known}} once on my behalf? Even a one-line \"FYI, just re-flagging the referral I sent {{referral_date}}\" goes a long way. If you'd rather not, completely fine — and if the req status has changed, even a \"yes, the role closed\" is the most useful answer.\n\nI don't want to be a pest, so this is the last nudge I'll send unless you want me to keep you in the loop.\n\nThanks,\n{{your_name}}\n{{your_linkedin_url}}", ["alum_first_name", "company", "hm_name_or_team", "referral_date", "role", "team", "your_linkedin_url", "your_name"], ["NEU alumni referral", "rate: 50-60%（warm tie + low-friction ask）"], "校友 refer 你 3+ 周前，你没有任何 hiring manager 回音；让校友帮你 nudge 内部。\n\n注意事项：\n- 这是 Hunter \"smaller ask\" 原则 — 让校友\"ping 一次\"，而不是\"fight for me\"。\n- 给校友 a graceful exit（\"If you'd rather not, completely fine\"）— 否则你在 build social debt。"),
  t("z04-c5", "C5 · 给 NEU 同级校友（peer level）— 共谋刷题 / mock interview", "referral_request", "MS Analytics '26 — mock interview swap?", "Hi {{alum_first_name}},\n\nSame cohort, different track — I'm {{your_name}}, MS Analytics '26, focusing on {{your_specialty}}. I saw you're going for {{target_role_type}} roles in {{target_industry}}.\n\nTrade idea: 2 mock interviews, each side picks the format the other needs. I'm strongest on {{your_strength, e.g., \"SQL + product sense cases\"}} and weakest on {{your_weakness, e.g., \"system design for ML platforms\"}}.\n\nIf you're game, I'll send 3 time options in {{time_window}} and we can pick whichever works. If not, no worries — and if you know another '26 Husky who'd be into this, an intro is appreciated.\n\n{{your_name}}\n{{your_linkedin_url}}", ["alum_first_name", "target_industry", "target_role_type", "time_window", "your_linkedin_url", "your_name", "your_specialty", "your_strength", "your_weakness"], ["NEU alumni referral", "rate: 30-50%（同级同学同 cohort 内 reciprocity 很强）"], "找同级校友互相 mock 面试 / 模拟 HM round；不是 referral，是 preparation partnership。\n\n注意事项：\n- peer-level mock partner 不属于 referral 但属于 alumni-driven job search — NEU Khoury 的 co-op 文化鼓励这种 cooperation。"),
  t("z04-c6", "C6 · 给 NEU Alumni Mentor（通过官方 Mentor Program）", "referral_request", "NEU Alumni Mentor Program — first meeting?", "Hi {{mentor_first_name}},\n\nThank you for signing up as a mentor with Northeastern's Alumni Mentor Program — I was matched with you as {{your_name}}, MS Analytics '26, targeting {{target_role_type}} roles starting {{start_window}}.\n\nQuick snapshot so we can skip the small talk on our first call:\n- Background before NEU: {{pre_neu_background, e.g., \"3 years as a data analyst at {{company_1}}\"}}\n- Co-op: {{coop_company_and_outcome}}\n- Capstone: {{capstone_topic}}\n- Open questions for you: {{list_2_3_questions, e.g., \"1) What's the realistic entry path for {{target_function}} at {{target_industry}}? 2) Which of my projects would you lead with in interviews? 3) How should I be thinking about {{specific_decision, e.g., \"startup vs. larger co. for first post-grad role\"}}?\"}}\n\nSuggested agenda for {{first_call_window}} (45 min):\n- 10 min — your background and {{target_function}} career path\n- 15 min — my projects / resume review\n- 15 min — open Q&A\n- 5 min — next steps + cadence\n\nIf you'd like to adjust, please pick whatever slots work best on your side. Thanks again for the time.\n\n{{your_name}}\n{{your_linkedin_url}} · {{your_phone}}", ["capstone_topic", "company_1", "coop_company_and_outcome", "first_call_window", "list_2_3_questions", "mentor_first_name", "pre_neu_background", "specific_decision", "start_window", "target_function", "target_industry", "target_role_type", "your_linkedin_url", "your_name", "your_phone"], ["NEU alumni referral", "rate: 80-95%（mentor 报名了 program，预期接触）"], "Northeastern 校友导师项目匹配到一位 mentor；首次接触邮件。\n\n注意事项：\n- NEU Alumni Mentor Program 走 **careers.northeastern.edu** 上的 HuskyCareer Network / Mentor Program 入口（这是合规官方触达渠道）。不要 cold 校友 mentor 列表外的真人。"),
  t("z04-d1", "D1 · Application 后 7 天 follow-up（\"any update\" 软版）", "follow_up", "Quick check — {{role}} application", "Hi {{first_name}},\n\nFollowing up on my {{role}} application from {{application_date}}. I know reqs move at their own pace, and I don't want to clutter your queue — just one quick question:\n\nIs there anything I can add to my application that would help your team move it forward? I have {{1_extra_asset, e.g., \"a 1-page write-up on {{specific_problem}} in {{industry}}\"}} ready to share if useful.\n\nEither way, thank you for considering my application.\n\n{{your_name}}\n{{your_phone}} · {{your_linkedin_url}}", ["1_extra_asset", "application_date", "first_name", "industry", "role", "specific_problem", "your_linkedin_url", "your_name", "your_phone"], ["Application follow-up", "rate: 8-12%"], "注意事项：\n- Hunter 数据：跟进 #1 是回复率峰值（https://hunter.io/blog/the-2026-anti-cold-emailer-mentality.md）。7 天是 sweet spot — Salesforce 经验 \"a few days afterwards\" 是标准。\n- **不要**写\"just checking in\"或\"hope this finds you well\" — Hunter \"anti-gimmick\" 红线。"),
  t("z04-d2", "D2 · Application 后 14 天 follow-up（价值升级版）", "follow_up", "Adding context to my {{role}} application", "Hi {{first_name}},\n\nTwo weeks since I applied for the {{role}} position, and I wanted to share a quick update rather than ping you with another \"any news?\".\n\nSince applying on {{application_date}}, I:\n- {{new_credential_1, e.g., \"wrapped my co-op presenting results to {{client_or_partner}}'s leadership\"}}\n- {{new_credential_2, e.g., \"added {{tool_or_cert}} to my stack\"}}\n\nMy interest in {{company}} is unchanged — your team's work on {{specific_initiative}} still lines up best with what I want to do next. If the role has shifted, paused, or been filled, I'd appreciate a 1-line update; if not, I'll plan to follow up once more in {{next_check_in, e.g., \"early Q1\"}}.\n\nThanks,\n{{your_name}}\n{{your_phone}} · {{your_linkedin_url}}", ["application_date", "client_or_partner", "company", "first_name", "new_credential_1", "new_credential_2", "next_check_in", "role", "specific_initiative", "tool_or_cert", "your_linkedin_url", "your_name", "your_phone"], ["Application follow-up", "rate: 6-10%"], "注意事项：\n- Hunter \"give-first\" 心理学（https://hunter.io/blog/3-psychology-backed-ways-to-get-more-email-replies-in-2026.md）：每封跟进都带**新 value**（新成就 / 新角度 / 新问题），不是同样的 nudge。\n- Salesforce \"Following up on my request\" 模板说\"few days afterwards\"，14 天是 application 节奏下更现实。"),
  t("z04-d3", "D3 · Application 后 30 天 follow-up（last check-in / graceful close）", "follow_up", "Closing the loop — {{role}} at {{company}}", "Hi {{first_name}},\n\nIt's been about a month since I applied for the {{role}} opening at {{company}}. I haven't heard back, and I want to close the loop cleanly on my side rather than keep applying pressure.\n\nIf the role is still open and you need more from me — additional materials, an interview slot — please let me know and I'll respond within 24 hours.\n\nIf the role has been filled, paused, or my application isn't moving forward for any reason, the most useful single reply would be one of:\n- \"Closed\" → I stop following up\n- \"Try again in {{future_window}}\" → I'll note it on my tracker\n- \"Reach out to {{alt_contact}}\" → I'll switch to that channel\n\nEither way, thank you for your time.\n\n{{your_name}}\n{{your_phone}} · {{your_linkedin_url}}", ["alt_contact", "company", "first_name", "future_window", "role", "your_linkedin_url", "your_name", "your_phone"], ["Application follow-up", "rate: 10-15%（最后一次 grace close 触发 \"oh actually\" 答复的概率出乎意料地高）"], "注意事项：\n- 这跟 Hunter \"rejection-then-retreat\" 一致 — 给 recruiter 三个最小承诺的 reply options，10 秒回复率历史最高。\n- 30 天后还无音一般意味已经走 dead path，主动 close 把 dignity 留给双方。"),
  t("z04-e1", "E1 · 面试后 24 小时内 thank-you note — 标准", "thank_you", "Thanks for the {{round_type}} chat — {{your_name}}", "Hi {{interviewer_first_name}},\n\nThank you for taking the time to speak with me about the {{role}} position at {{company}} on {{interview_date}}. I especially appreciated our discussion of {{specific_topic_you_discussed, e.g., \"your team's approach to experimentation cadence\"}} — it sharpened my thinking on {{specific_application, e.g., \"how I'd approach {{problem_in_role}} in the first 90 days\"}}.\n\nTwo quick follow-ups from the conversation:\n1. {{follow_up_1, e.g., \"the link to the case study I mentioned is attached\"}}\n2. {{follow_up_2, e.g., \"my answer about {{technical_topic}} — I want to add the {{specific_clarification}} reference we ran out of time for\"}}\n\nI'm genuinely excited about the {{team_or_function}} work at {{company}} and look forward to hearing back from {{recruiter_or_next_step_owner}} about next steps. Please don't hesitate to reach out if anything else would be useful.\n\nBest,\n{{your_name}}\n{{your_phone}} · {{your_linkedin_url}}", ["company", "follow_up_1", "follow_up_2", "interview_date", "interviewer_first_name", "problem_in_role", "recruiter_or_next_step_owner", "role", "specific_application", "specific_clarification", "specific_topic_you_discussed", "team_or_function", "technical_topic", "your_linkedin_url", "your_name", "your_phone"], ["Post-interview", "rate: 80-90%（内部数据显示 thank-you 极少被忽略；正面影响 HM 评分）"], "任何面试（phone screen / technical / onsite）结束后 24 小时内。\n\n注意事项：\n- Workable 数据：24 小时内是黄金窗口，before candidate reaches out to you（https://resources.workable.com/tutorial/follow-up-email-after-interview）。纯文本 + 无附件链接，attachment 在第二封 reply 后再发（Hunter deliverability 指南）。\n- 每个面试官**单独发** thank-you，不要 cc 全部人 — Workable 强调 personal touch。"),
  t("z04-e2", "E2 · 面试后 thank-you 给 recruiter（确认 timeline）", "thank_you", "Thanks — {{role}} at {{company}}", "Hi {{recruiter_first_name}},\n\nThanks for setting up the {{interview_round, e.g., \"technical round\"}} with {{interviewer_name}} on {{interview_date}}. The conversation about {{specific_topic}} gave me a clearer picture of what {{company}} is looking for in this role.\n\nOne quick logistical question: based on the timeline you mentioned ({{recruiter's_stated_eta, e.g., \"next Friday\"}}), when would be the right time for me to follow up if I haven't heard back? I don't want to pester — just want to make sure I'm tracking the right cadence.\n\nIn the meantime, please pass on my thanks to {{interviewer_name}} — I appreciated the {{specific_aspect}}.\n\nBest,\n{{your_name}}\n{{your_phone}} · {{your_linkedin_url}}", ["company", "interview_date", "interview_round", "interviewer_name", "recruiter", "recruiter_first_name", "specific_aspect", "specific_topic", "your_linkedin_url", "your_name", "your_phone"], ["Post-interview", "rate: 70-85%"], "注意事项：\n- Workable 数据：recruiter 重视 \"open communication\"，主动询问 timeline 是 professional maturity 信号。\n- 注意 answer: keep it short — recruiter 邮件 inbox 经常 200+ / 天。"),
  t("z04-e3", "E3 · 面试后 7 天 — 中段 follow-up", "thank_you", "Status check — {{role}} at {{company}}", "Hi {{recruiter_first_name}},\n\nFollowing up on the {{interview_round}} we ran on {{interview_date}} for the {{role}} role at {{company}}. You mentioned a {{recruiter's_stated_eta}} decision window — just checking in to see if anything on my side would help you move it forward.\n\nIf it's still in progress, no action needed from me. If anything has changed — paused, filled, or delayed — even a one-line update is useful so I can plan my search accordingly.\n\nThanks,\n{{your_name}}\n{{your_phone}} · {{your_linkedin_url}}", ["company", "interview_date", "interview_round", "recruiter", "recruiter_first_name", "role", "your_linkedin_url", "your_name", "your_phone"], ["Post-interview", "rate: 60-70%"], "面试官说 \"we'll get back in a week\"，7 天后无消息。\n\n注意事项：\n- Hunter \"smaller ask\" 原则：给对方单一明确选择（\"still in progress\" vs \"one-line update\"）。"),
  t("z04-e4", "E4 · 面试后 silence 后最后一封（断点）", "thank_you", "Closing the loop — {{role}} at {{company}}", "Hi {{recruiter_first_name}},\n\nIt's been {{time_since_interview}} since my final round for the {{role}} role at {{company}}. I haven't heard back despite your earlier {{recruiter's_stated_eta}} estimate.\n\nBefore I close this out on my side, one quick question: is the role still active, and is there anything I should know that would explain the silence?\n\nIf you've already moved forward with another candidate, congratulations to the team — and please don't feel obligated to reply. If the role has paused or there was a process issue, even a one-line honest answer helps me improve my approach for next time.\n\nWishing {{company}} the best,\n{{your_name}}\n{{your_linkedin_url}}", ["company", "recruiter", "recruiter_first_name", "role", "time_since_interview", "your_linkedin_url", "your_name"], ["Post-interview", "rate: 30-45%（silence 之后 graceful close 经常触发 honest reply）"], "注意事项：\n- Workable 数据：候选人最大 complaint 是 \"uncertainty and lack of communication\"。给 recruiter 一个 dignified exit 让 ta 愿意 reply。\n- 千万别 accusatory（\"I haven't heard back despite...\"）— 改成 neutral timeline anchor。"),
  t("z04-f1", "F1 · 被拒后 ask for feedback（不抱怨、不卑不亢）", "post_rejection", "{{role}} — feedback request", "Hi {{recruiter_or_hm_first_name}},\n\nThank you for letting me know about your decision on the {{role}} role. I appreciate the time {{company}} invested in my candidacy, especially {{specific_positive_aspect_of_process, e.g., \"the technical round with {{interviewer_name}}\"}}.\n\nIf you have a moment, I'd be grateful for any feedback you can share — specifically:\n- {{focus_area_1, e.g., \"where my technical depth fell short relative to the strongest candidates\"}}\n- {{focus_area_2, e.g., \"whether my project examples communicated impact clearly\"}}\n\nI understand if you're not able to share specifics. If there's a more appropriate person (e.g., the hiring manager) who'd be willing to spend 10 minutes walking me through their decision, an intro would also be hugely appreciated.\n\nEither way, thank you again — I'll be cheering for {{company}}'s next hire.\n\nBest,\n{{your_name}}\n{{your_linkedin_url}}", ["company", "focus_area_1", "focus_area_2", "interviewer_name", "recruiter_or_hm_first_name", "role", "specific_positive_aspect_of_process", "your_linkedin_url", "your_name"], ["After rejection", "rate: 25-40%（ask 反馈比 ask re-apply 难度低；很多 recruiter 在 rejection 后愿意 share 简短 insight）"], "注意事项：\n- 一定要 **thank them first**（reciprocity），再 ask；不能把 feedback ask 写成 \"please explain why you rejected me\"。\n- Many companies have policy against giving candidate feedback，so 接受 \"we can't share specifics\" as 完全 valid 答复。"),
  t("z04-f2", "F2 · 被拒后 6 个月重新进场（已经改进）", "post_rejection", "Update + re-consider — {{role}} type", "Hi {{recruiter_first_name}},\n\nWhen we spoke in {{month_year_of_rejection}} about the {{role}} opening, you flagged {{specific_feedback_you_were_given, e.g., \"wanting stronger causal-inference experience beyond the standard A/B testing\"}} as the gap. I've spent the last {{time_window}} closing that:\n\n- {{credential_1, e.g., \"completed {{specific_course_or_project}} in causal inference / DiD / synthetic control\"}}\n- {{credential_2, e.g., \"applied the methods on {{coop_or_personal_project}} with {{outcome}}\"}}\n\nI'm now looking again at {{role_type}} roles starting {{start_window}}. If {{company}} has an opening that's a better fit than before, would you be open to a re-intro? If the same gap would still apply, \"still not the right role\" is a useful answer too.\n\nThanks for the original conversation,\n{{your_name}}\n{{your_linkedin_url}}", ["company", "coop_or_personal_project", "credential_1", "credential_2", "month_year_of_rejection", "outcome", "recruiter_first_name", "role", "role_type", "specific_course_or_project", "specific_feedback_you_were_given", "start_window", "time_window", "your_linkedin_url", "your_name"], ["After rejection", "rate: 15-25%"], "注意事项：\n- 这是 **Hunter \"single-question diagnostic\" + \"give-first\"** 的进阶版 — 把对方之前的反馈变成你改进的 hook。"),
  t("z04-f3", "F3 · 被拒后 networking thank-you（不求 rehire，求保持联系）", "post_rejection", "Thanks for the {{role}} process — staying in touch", "Hi {{hm_or_recruiter_first_name}},\n\nThank you for the {{role}} process — even though I didn't get the offer, the conversations about {{specific_topic_you_found_valuable, e.g., \"how your team approaches measurement\"}} genuinely shaped how I'm thinking about my next move.\n\nIf it's appropriate, I'd love to stay loosely connected on LinkedIn so I can keep learning from {{specific_artifact_they_publish, e.g., \"your team's blog\"}} and reach out in the future if a more aligned {{role_type}} opens up — either at {{company}} or in your extended network.\n\nNo expectation of action on your side. Just wanted to close on a good note.\n\nBest,\n{{your_name}}\n{{your_linkedin_url}}", ["company", "hm_or_recruiter_first_name", "role", "role_type", "specific_artifact_they_publish", "specific_topic_you_found_valuable", "your_linkedin_url", "your_name"], ["After rejection", "rate: 40-55%（low-ask、genuine thank-you；很多 HM 会 accept LinkedIn request 并 remember 你）"], "注意事项：\n- 这是 pure reciprocity / graceful exit — 不求 offer，只求 network retention。"),
  t("z04-g1", "G1 · 收到 offer 后第一封 — 表达兴趣 + ask for time", "salary_negotiation", "Offer received — {{role}} at {{company}}", "Hi {{recruiter_first_name}},\n\nThank you for the {{role}} offer at {{company}}. I'm genuinely excited about {{specific_aspect_of_role_you_loved, e.g., \"the {{specific_team_or_project}} scope\"}} and the team I met during the process.\n\nTo make a thoughtful decision, I'd appreciate {{negotiation_window, e.g., \"5 business days\"}} to review the offer details carefully and discuss with my partner / family. Could you confirm the latest possible response date so I can plan accordingly?\n\nI'll respond by {{specific_date}} either way. If it's helpful, I'm happy to set up a brief call before then to ask any final questions about the role or the team.\n\nBest,\n{{your_name}}\n{{your_phone}} · {{your_linkedin_url}}", ["company", "negotiation_window", "recruiter_first_name", "role", "specific_aspect_of_role_you_loved", "specific_date", "specific_team_or_project", "your_linkedin_url", "your_name", "your_phone"], ["Offer negotiation"], "注意事项：\n- 永远不要在 24h 内 sign — anchoring 需要 preparation window。\n\n---"),
  t("z04-g2", "G2 · Base salary counter（锚定高出 offer 的目标价）", "salary_negotiation", "Offer discussion — base salary component", "Hi {{recruiter_first_name}},\n\nThank you again for the {{role}} offer. The role, team, and mission are all exactly what I was hoping for, and I'm fully committed to moving forward.\n\nI want to discuss the base salary component. Based on {{data_source_1, e.g., \"Levels.fyi data for {{role_title}} at companies of {{company}}'s size and geography\"}} and {{data_source_2, e.g., \"recent conversations with {{peer_count}} peers in similar roles}}, the market range for this role appears to be {{market_range_low}}–{{market_range_high}}, with a median around {{market_median}}.\n\nGiven {{specific_value_you_bring, e.g., \"my {{specific_credential}} and {{specific_outcome}} at {{previous_or_coop_context}}\"}}, I'd like to discuss a base of {{target_base}}, which I believe aligns with the {{market_percentile, e.g., \"60th percentile\"}} for this scope.\n\nI want to be transparent: {{target_base}} is the number where I'd accept on the spot. Everything else in the package (signing bonus, equity, start date) is workable. If the base component can't move, I'd appreciate understanding what flexibility exists on the total comp to bridge the gap.\n\nCan we set up a 20-minute call this week to discuss?\n\nBest,\n{{your_name}}\n{{your_phone}} · {{your_linkedin_url}}", ["company", "data_source_1", "data_source_2", "market_median", "market_percentile", "market_range_high", "market_range_low", "peer_count", "previous_or_coop_context", "recruiter_first_name", "role", "role_title", "specific_credential", "specific_outcome", "specific_value_you_bring", "target_base", "your_linkedin_url", "your_name", "your_phone"], ["Offer negotiation"], "Base 比你的 target 低 $5-15K；用 market data + 对方 initial offer 做 anchor。\n\n注意事项：\n- **Anchoring 核心**：先给一个 **specific** 数字（\"60th percentile\"、\"target $X\"），而不是 \"more competitive\"。Recruiter 永远 will defend vagueness but bends to specifics。\n- 三个 data source：Levels.fyi / Glassdoor / 自家 alumni 数据都是公开 / 半公开。\n\n---"),
  t("z04-g3", "G3 · 谈判让步形状 A — Cash（base）优先", "salary_negotiation", "Comp discussion — {{role}}", "Hi {{recruiter_first_name}},\n\nThanks for the time on the call. To recap where we landed:\n\nYou're at {{current_base}} base; my target is {{target_base}} (delta: {{delta}}). On the equity side, you're at {{current_equity}} with {{vesting_schedule}}; that's reasonable, and I'll plan to evaluate the strike carefully when I receive the full grant details.\n\nWhere I have flexibility:\n- {{compromise_on, e.g., \"signing bonus of {{signing_bonus_target}} paid out over the first year\"}}\n- {{compromise_on, e.g., \"12-month performance review with explicit base adjustment conversation\"}}\n\nWhere I don't have flexibility:\n- Base below {{walkaway_base, e.g., \"$X\"}} is below the cost-of-living threshold I've committed to for {{city_or_remote}}.\n\nTo get this done, can we lock in {{final_proposed_base}} with a {{final_proposed_signing_bonus}} signing bonus? That hits my number, keeps the package simple, and I can sign by end of week.\n\nBest,\n{{your_name}}", ["city_or_remote", "compromise_on", "current_base", "current_equity", "delta", "final_proposed_base", "final_proposed_signing_bonus", "recruiter_first_name", "signing_bonus_target", "target_base", "vesting_schedule", "walkaway_base", "your_name"], ["Offer negotiation"], "注意事项：\n- 让步形状 A：cash-heavy — 大部分毕业生首要看 base，因为 RSUs 需要 1 年 cliff 才到手。signing bonus 是 second best，因为它一次性、不影响未来 base curve。\n\n---"),
  t("z04-g4", "G4 · 谈判让步形状 B — Equity-heavy（早期 startup 常见）", "salary_negotiation", "Equity component — {{role}}", "Hi {{recruiter_first_name}},\n\nThanks for the call. The base at {{current_base}} is workable given the company's stage and the equity upside potential. On the equity side, I'd like to discuss a few specifics:\n\n1. **Grant size:** Current offer is {{current_equity_shares}} shares at {{current_strike}}. Based on {{data_source, e.g., \"comparator grants for {{role_title}} at Series {{stage}} startups of similar size\"}}, the market range for this role is {{market_equity_low}}–{{market_equity_high}}.\n\n2. **Vesting:** Standard is 4-year / 1-year cliff. I'd like to confirm whether {{company}} offers:\n   - {{cliff_option, e.g., \"a partial mid-year cliff (e.g., 6-month cliff)\"}}\n   - {{acceleration_option, e.g., \"double-trigger acceleration on change-of-control\"}}\n\n3. **Exercise window post-departure:** I'd like to confirm whether the post-departure exercise window is {{exercise_window, e.g., \"the standard 90 days\"}} or extends longer (relevant if we go public / get acquired and I'd want time to manage the tax event).\n\nIf we can move the grant to {{target_equity_shares}} shares with the same strike, I'm ready to sign. If grant movement isn't possible, I'd ask for a {{target_signing_bonus}} signing bonus to bridge.\n\nBest,\n{{your_name}}\n{{your_phone}} · {{your_linkedin_url}}", ["acceleration_option", "cliff_option", "company", "current_base", "current_equity_shares", "current_strike", "data_source", "exercise_window", "market_equity_high", "market_equity_low", "recruiter_first_name", "role_title", "stage", "target_equity_shares", "target_signing_bonus", "your_linkedin_url", "your_name", "your_phone"], ["Offer negotiation"], "注意事项：\n- 让步形状 B：equity-heavy — 多问 vesting / acceleration / exercise window，**不要**只问 share count。\n- 早期 startup 一般 base 低但 equity 高 — cash negotiation 不动，equity 有空间。\n\n---"),
  t("z04-g5", "G5 · 谈判让步形状 C — Signing bonus / relocation / start date", "salary_negotiation", "Final adjustments — {{role}}", "Hi {{recruiter_first_name}},\n\nI appreciate the back-and-forth. The base at {{final_base}} and equity at {{final_equity}} are workable for the role. To bridge the remaining delta on total first-year value, I'd like to discuss three optional components:\n\n1. **Signing bonus of {{signing_bonus_target}}**, ideally paid out in {{payout_schedule, e.g., \"the first regular paycheck after start\"}} to help with {{specific_use, e.g., \"relocation to {{city}} and the {{specific_expense}} upfront cost\"}}.\n\n2. **Relocation support:** If {{company}} has a standard relocation package, please share it; if not, a one-time {{relocation_lump_sum}} would replace per-diem.\n\n3. **Start date:** I'd like to start on {{target_start_date}} rather than {{original_start_date}}. Reasons: {{specific_reason, e.g., \"completing my NEU capstone presentation on {{capstone_defense_date}}\"}}. This also gives me {{benefit_to_employer, e.g., \"two weeks to wrap personal logistics before joining cleanly\"}}.\n\nAny combination of the above totaling the {{target_total_delta}} first-year delta would let me sign.\n\nBest,\n{{your_name}}\n{{your_phone}} · {{your_linkedin_url}}", ["benefit_to_employer", "capstone_defense_date", "city", "company", "final_base", "final_equity", "original_start_date", "payout_schedule", "recruiter_first_name", "relocation_lump_sum", "signing_bonus_target", "specific_expense", "specific_reason", "specific_use", "target_start_date", "target_total_delta", "your_linkedin_url", "your_name", "your_phone"], ["Offer negotiation"], "注意事项：\n- 让步形状 C：cash/equity 已经谈判完，剩 structural components。\n- Signing bonus 一般一次性，不影响未来 base curve，所以是\"无后遗症\"补偿。\n\n---\n\n## H. 多 offer 比较 / 延期决定 / 撤回（4 套）"),
  t("z04-h1", "H1 · 多 offer 同时在桌 — 透明化时间线", "salary_negotiation", "Offer timeline — {{role}} at {{company}}", "Hi {{recruiter_first_name}},\n\nI want to be transparent about my timeline so you can plan accordingly:\n\n- I have {{count_other_offers, e.g., \"two\"}} other active processes I'm working through.\n- {{company_other_1}} is asking for a response by {{other_deadline_1}}.\n- {{company_other_2}} is at the {{other_stage_2, e.g., \"final round, expected offer by {{other_date_2}}\"}}.\n\nMy strong preference is {{company}}, and I want to give your team a fair chance to close the loop. Two requests:\n\n1. If possible, accelerate any remaining {{company}} steps so I can make a decision with full information. The earliest I could realistically sign with {{company}} is {{earliest_sign_date}}.\n2. If acceleration isn't feasible, please give me your best estimate of when you'll have a final decision, so I can plan around it honestly.\n\nI won't string you along — once I have a definitive timeline from you, I'll commit to it (or decline cleanly if it doesn't work).\n\nBest,\n{{your_name}}\n{{your_phone}} · {{your_linkedin_url}}", ["company", "company_other_1", "company_other_2", "count_other_offers", "earliest_sign_date", "other_date_2", "other_deadline_1", "other_stage_2", "recruiter_first_name", "your_linkedin_url", "your_name", "your_phone"], ["Multi-offer / deferral"], "注意事项：\n- 永远 honest — Hunter \"anti-cold emailer\" 强调 genuine communication。Recruiter 内部对 candidate dishonesty 极度敏感。\n\n---"),
  t("z04-h2", "H2 · 延期决定请求（延长 sign deadline）", "salary_negotiation", "Decision deadline — {{role}} at {{company}}", "Hi {{recruiter_first_name}},\n\nThank you for the {{role}} offer at {{company}}. I'm working toward a decision and want to give it the care it deserves. Could I have until {{new_requested_deadline}} to respond, rather than the original {{original_deadline}}?\n\nThe reason for the extension: {{honest_reason, e.g., \"I'm finishing my NEU capstone defense on {{defense_date}} and want to make this decision with full focus on {{decision_criteria}}\"}}.\n\nI want to be transparent: I'm not using the extension to shop for competing offers — I'm genuinely working through the decision framework I committed to before your offer came in.\n\nIf an extension isn't possible, I'll do my best with the original timeline.\n\nBest,\n{{your_name}}\n{{your_phone}} · {{your_linkedin_url}}", ["company", "decision_criteria", "defense_date", "honest_reason", "new_requested_deadline", "original_deadline", "recruiter_first_name", "role", "your_linkedin_url", "your_name", "your_phone"], ["Multi-offer / deferral"], "注意事项：\n- 标准延期请求是 3-7 天；超过 10 天 recruiter 会 start doubting your seriousness。\n- 给**具体理由**（defense date / family discussion / 其他 process 完成）— vague \"I need more time\" 是低质信号。\n\n---"),
  t("z04-h3", "H3 · 撤回 offer（你决定不去）", "salary_negotiation", "Withdrawing from {{role}} at {{company}}", "Hi {{recruiter_first_name}},\n\nAfter careful consideration, I've decided not to accept the {{role}} offer at {{company}} at this time. I want to let you know promptly rather than leave the offer hanging.\n\nThe decision came down to {{honest_reason_short, e.g., \"alignment with another opportunity that better matches my long-term goal of {{specific_goal}}\"}}. This isn't a reflection on {{company}}, the team, or the role — I had a genuinely positive experience through the process, especially {{specific_positive_aspect, e.g., \"the conversations about {{topic}} with {{interviewer_name}}\"}}.\n\nWould you be open to me staying loosely in touch for future {{role_type}} opportunities that might be a better fit? Either way, thank you for the time your team invested.\n\nBest,\n{{your_name}}\n{{your_linkedin_url}}", ["company", "honest_reason_short", "interviewer_name", "recruiter_first_name", "role", "role_type", "specific_goal", "specific_positive_aspect", "topic", "your_linkedin_url", "your_name"], ["Multi-offer / deferral"], "注意事项：\n- **永远 prompt** 撤回 — 不要 drag；让 recruiter 立刻启动 backup candidate。\n- 给 honest reason 但**不要** detail 哪家 offer 你拿了 — 这是 recruiter 行业规范。\n\n---"),
  t("z04-h4", "H4 · 公司撤回 offer 后 ask for explanation / reprieve", "salary_negotiation", "Offer status — urgent question", "Hi {{recruiter_first_name}},\n\nI just received the update about the {{role}} offer being rescinded / paused. Before I react, can we set up a 15-minute call today or tomorrow to discuss:\n\n1. The specific reason — is this role-specific (e.g., the req was eliminated), company-wide (e.g., hiring freeze), or candidate-specific (e.g., a concern about my background we can address)?\n2. Whether any alternative exists — a deferred start, a different role on the same team, contract-to-hire, or relocation to a different office.\n3. Whether you'd be willing to write a referral to a peer company or be a reference for me given the situation.\n\nI understand these dynamics can be outside your control. Whatever the answer, I'd appreciate honesty and a documented explanation I can reference if needed for future applications or visa-related processes.\n\nBest,\n{{your_name}}\n{{your_phone}} · {{your_linkedin_url}}", ["recruiter_first_name", "role", "your_linkedin_url", "your_name", "your_phone"], ["Multi-offer / deferral"], "注意事项：\n- Offer 撤回对 Zihao 这种 12 月毕业、OPT/CPT 时点敏感的国际生尤其严重 — 一定要 ask for documentation（书面 explanation）。可以引用 USCIS / 移民律师需要 \"evidence of bona fide offer\" 这一点（如果对方撤回 offer 后你仍需要维持 status）。\n\n---\n\n## I. LinkedIn 300 字符 connection note（5 套 — 都 ≤ 300 chars）\n\n> LinkedIn 公共 UI 限制：connection request note 上限 300 字符（这是 LinkedIn 在 connection request modal 上方持续显示的 char counter，publicly visible in product）。下面每条都字符计数验证。"),
  t("z04-i1", "I1 · 给 Recruiter（260 chars）", "networking", "(no subject line — LinkedIn note (≤300))", "Hi {{first_name}} — Northeastern MS Analytics '26, interested in {{target_function}} roles at {{company}}. Saw your active reqs and would love to be on your radar. — {{your_name}}", ["company", "first_name", "target_function", "your_name"], ["LinkedIn note (≤300)", "no-subject channel"], ""),
  t("z04-i2", "I2 · 给 Hiring Manager（280 chars）", "networking", "(no subject line — LinkedIn note (≤300))", "Hi {{first_name}} — {{your_name}}, MS Analytics '26 at Northeastern. Your team's work on {{specific_topic}} matches my background in {{one_keyword}}. Would love to connect, not pitching anything today.", ["first_name", "one_keyword", "specific_topic", "your_name"], ["LinkedIn note (≤300)", "no-subject channel"], ""),
  t("z04-i3", "I3 · 给 NEU 校友 — fellow Husky（225 chars）", "networking", "(no subject line — LinkedIn note (≤300))", "Hi {{alum_first_name}} — fellow Husky here ('26 Analytics). Saw you're at {{alum_company}} doing {{alum_function}}. Would love to connect and learn from your path.", ["alum_company", "alum_first_name", "alum_function"], ["LinkedIn note (≤300)", "no-subject channel"], ""),
  t("z04-i4", "I4 · 给行业从业者 — 纯 networking（210 chars）", "networking", "(no subject line — LinkedIn note (≤300))", "Hi {{first_name}} — {{your_name}}, MS Analytics '26 at Northeastern. Really enjoyed your {{specific_artifact}} on {{topic}}. Would love to follow your work.", ["first_name", "specific_artifact", "topic", "your_name"], ["LinkedIn note (≤300)", "no-subject channel"], ""),
  t("z04-i5", "I5 · 给 Informational interview 校友（295 chars）", "networking", "(no subject line — LinkedIn note (≤300))", "Hi {{alum_first_name}} — {{your_name}} here, MS Analytics '26 at Northeastern. Targeting {{role_type}} roles starting {{start_window}}. Would value 15 min of your time on {{company_or_function}} entry paths.", ["alum_first_name", "company_or_function", "role_type", "start_window", "your_name"], ["LinkedIn note (≤300)", "no-subject channel"], ""),
  t("z04-j1", "J1 · 给行业 KOL — informational", "networking", "(no subject line — X / Twitter DM)", "Hey {{handle}} — {{your_name}}, MS Analytics '26 at Northeastern. Long-time reader of your {{thread_topic}} threads. One question I keep getting from classmates that I think you'd have the clearest answer to: {{specific_question}}.\n\nNot asking for a meeting — even a 2-sentence DM back is hugely helpful. Thanks for all the public writing.", ["handle", "specific_question", "thread_topic", "your_name"], ["X / Twitter DM", "no-subject channel"], "X / Twitter 上活跃的 analytics KOL 偶尔回答 DM。\n\n注意事项：\n- 简短 + specific question = 高 reply 概率。KOL 时间稀缺，respect it。\n- 不要 attach link / 推销自己 — 直接 ask 知识。\n\n---"),
  t("z04-j2", "J2 · 给创始人 / 小公司 hiring lead", "networking", "(no subject line — X / Twitter DM)", "Hi {{handle}} — congrats on {{recent_company_news}}. I'm {{your_name}}, MS Analytics '26 at Northeastern, interested in {{target_function}} at {{company}}.\n\nTwo questions:\n1. Are you hiring for {{target_role_type}} in the next 1-2 quarters?\n2. If yes, who on your team should I send a 1-page project write-up to?\n\nEither way, thanks for the time.", ["company", "handle", "recent_company_news", "target_function", "target_role_type", "your_name"], ["X / Twitter DM", "no-subject channel"], "注意事项：\n- X DM 的 founder 比 LinkedIn InMail 更可能 read（private channel）。\n\n---\n\n## K. GitHub / Open Source 切入（3 套）"),
  t("z04-k1", "K1 · 给开源项目 maintainer — first PR / first issue", "networking", "(no subject line — GitHub / OSS)", "Hi {{maintainer_handle}},\n\nI'm {{your_name}}, MS Analytics '26 at Northeastern, and I've been using {{project_name}} for {{use_case, e.g., \"my cohort retention analysis on {{dataset}}\"}}.\n\nI'd like to contribute. Before I open a PR, two questions:\n\n1. Are there any \"good first issue\" / \"help wanted\" tags currently open that you'd recommend a first-time contributor start with? I've looked through the issue tracker and noticed {{specific_issue_or_pattern}}.\n\n2. Is there a contributor guideline / coding style doc beyond CONTRIBUTING.md I should follow? I noticed {{specific_observation_about_repo, e.g., \"the test coverage pattern in {{path}}\"}}.\n\nI want to keep my first contribution narrow and high-quality — happy to start with a documentation fix or a single, well-scoped code change rather than a sweeping refactor.\n\nThanks for maintaining {{project_name}},\n{{your_name}}\n{{your_github_handle}}", ["dataset", "maintainer_handle", "path", "project_name", "specific_issue_or_pattern", "specific_observation_about_repo", "use_case", "your_github_handle", "your_name"], ["GitHub / OSS", "no-subject channel"], "想通过 contribute 到某个公司维护的开源项目做\"软内推\"。第一次贡献前 maintainer 接触。\n\n注意事项：\n- **不要**第一封就把求职目的写出来 — Hunter \"give-first\" 心理学：先 prove 你能 contribute，再谈工作。\n- GitHub profile / commit history 是 silent resume — maintainer 会自己 look up。\n\n---"),
  t("z04-k2", "K2 · 给 maintainer — 已贡献 2-3 个 PR 后，软提工作", "networking", "(no subject line — GitHub / OSS)", "Hi {{maintainer_handle}},\n\nQuick update on my end: my contributions to {{project_name}} ({{list_pr_numbers_or_links}}) wrapped a few weeks ago, and I'm now in active job-search mode for {{target_role_type}} roles starting {{start_window}}.\n\nTwo questions:\n1. If {{maintainer_company}} has any {{target_function}} openings in the next two quarters, would you be willing to look at my background / forward a note internally?\n2. If not directly applicable, do you know other maintainers / engineers at companies in {{target_industry}} who'd value the same kind of open-source track record?\n\nNo pressure on either — appreciate the time either way.\n\n{{your_name}}\n{{your_github_handle}} · {{your_linkedin_url}}", ["list_pr_numbers_or_links", "maintainer_company", "maintainer_handle", "project_name", "start_window", "target_function", "target_industry", "target_role_type", "your_github_handle", "your_linkedin_url", "your_name"], ["GitHub / OSS", "no-subject channel"], "你已经成功 merged 1-2 个 PR 后，maintainer 知道你了。\n\n注意事项：\n- 软触达，不硬 ask；你已经有 credibility base（merged PRs）。\n\n---"),
  t("z04-k3", "K3 · 给公司招聘 / engineering blog — 基于 contribution 的自我介绍", "networking", "(no subject line — GitHub / OSS)", "Hi {{editor_first_name}},\n\nI'm {{your_name}}, MS Analytics '26 at Northeastern. I recently contributed {{specific_contribution, e.g., \"a performance optimization to {{project_name}} that reduced query time by 40%\"}} and thought the {{engineering_blog_name}} might be interested in a technical write-up.\n\nProposed angle: a 1,500-word piece on {{specific_technical_angle, e.g., \"how I profiled query latency in {{tool_name}} and what I learned about {{library_name}}'s internals\"}}.\n\nI don't need to be paid or credited in any specific way — I'm happy with a standard contributor post if your editorial team finds it useful. If you're not the right person, an intro to the engineering blog editor would be appreciated.\n\nThanks for considering,\n{{your_name}}\n{{your_github_handle}} · {{your_linkedin_url}}", ["editor_first_name", "engineering_blog_name", "library_name", "project_name", "specific_contribution", "specific_technical_angle", "tool_name", "your_github_handle", "your_linkedin_url", "your_name"], ["GitHub / OSS", "no-subject channel"], "你给 {{company}} 维护的开源项目做了重要 contribution；通过 engineering blog 联系 editor。\n\n注意事项：\n- Engineering blog post 是 stealth resume — many companies 把 author 看作 future candidate。\n\n---\n\n## L. Informational interview 邀约 + 后续（3 套）"),
  t("z04-l1", "L1 · Informational interview 邀约（给陌生人）", "networking", "15-min coffee chat? — {{your_name}}, NEU '26", "Hi {{first_name}},\n\nI'm {{your_name}}, MS Analytics '26 at Northeastern (Khoury), and I'm researching career paths in {{target_function}}. Your background on {{specific_artifact, e.g., \"your {{medium}} piece on {{topic}} / your role on {{team}} at {{company}}\"}} lines up directly with the direction I'm considering.\n\nA 15-minute virtual coffee chat would be hugely valuable — three questions I'd love your perspective on:\n1. {{question_1, e.g., \"What's a typical day for someone in {{role}} at {{company_stage}}\"}}\n2. {{question_2, e.g., \"What skills do you wish you'd built earlier\"}}\n3. {{question_3, e.g., \"How do you see {{target_function}} evolving over the next 2-3 years\"}}\n\nI'm flexible on time and happy to work around your schedule. If you're slammed, a 2-3 sentence email response on any of those three questions is the next best thing.\n\nThanks for considering,\n{{your_name}}\n{{your_linkedin_url}}", ["company", "company_stage", "first_name", "medium", "question_1", "question_2", "question_3", "role", "specific_artifact", "target_function", "team", "topic", "your_linkedin_url", "your_name"], ["Informational interview", "rate: 15-25%（cold informational request；AeroChat 经验：高度 targeted + 高质量 → 高 reply）"], ""),
  t("z04-l2", "L2 · Informational chat 后 — thank-you + soft re-engage", "networking", "Thank you + one follow-up", "Hi {{first_name}},\n\nThank you for the {{chat_date}} chat — three things I wrote down:\n\n1. {{key_takeaway_1}}\n2. {{key_takeaway_2}}\n3. {{key_takeaway_3}}\n\nThe {{specific_advice_you_gave, e.g., \"point about experimenting on cohort retention\"}} is already changing how I'm approaching {{specific_application, e.g., \"my final project\"}} — thank you for the directness.\n\nOne small follow-up: you mentioned {{name_or_company}} in passing. If you'd be willing to make an email intro, that would be the next step on my side. If you'd rather stay out of it, completely understood.\n\nI'll plan to reconnect in {{re_engage_window, e.g., \"3 months\"}} with an update on how your advice played out — assuming you'd welcome that.\n\nThanks again,\n{{your_name}}\n{{your_linkedin_url}}", ["chat_date", "first_name", "key_takeaway_1", "key_takeaway_2", "key_takeaway_3", "name_or_company", "re_engage_window", "specific_advice_you_gave", "specific_application", "your_linkedin_url", "your_name"], ["Informational interview", "rate: 60-75%（warm follow-up after informational）"], ""),
];

// Alternate subject lines the report offered for each template (variant 2 and 3).
export const templateAltSubjects: Record<string, string[]> = {
 "z04-a1": [
  "NEU Analytics grad → {{role}} at {{company}}",
  "Following up: {{role}} application ({{first_name}})"
 ],
 "z04-a2": [
  "Re: {{role}} — quick update",
  "{{first_name}}, one more try on {{role}}"
 ],
 "z04-a3": [
  "Quick intro: MS Analytics, {{specialty}} focus",
  "{{first_name}}, profile for your {{specialty}} pipeline"
 ],
 "z04-a4": [
  "{{first_name}}, a year-later re-intro",
  "Re-adding to your {{function}} bench — {{your_name}}"
 ],
 "z04-a5": [
  "Proactive: {{your_name}} for a {{function}} role that doesn't exist yet",
  "{{first_name}}, candidate for your next {{function}} req"
 ],
 "z04-b1": [
  "{{first_name}}, question on {{team}}'s {{time_window}} plan",
  "Idea worth 10 minutes — {{team}} at {{company}}"
 ],
 "z04-b2": [
  "Following up on {{alum_first_name}}'s note — {{your_name}}",
  "Intro via {{alum_first_name}} (NEU 'XX) — {{role_type}} candidate"
 ],
 "z04-b3": [
  "{{topic}} — one idea from your {{artifact_type}}",
  "{{first_name}}, follow-up on the {{topic}} piece"
 ],
 "z04-b4": [
  "Should I stop reaching out?",
  "One final note — {{team}} at {{company}}"
 ],
 "z04-b5": [
  "{{first_name}}, can I take 1 minute of someone on {{team}}'s time?",
  "Tiny ask: a 20-min intro for a {{role_type}} prospect"
 ],
 "z04-c1": [
  "{{alum_first_name}}, fellow Husky asking for 15 min",
  "Coffee chat? {{your_name}}, MS Analytics '26"
 ],
 "z04-c2": [
  "Following up on our {{chat_date}} conversation",
  "Internal referral — comfortable for you?"
 ],
 "z04-c3": [
  "Quick yes/no — would you refer me?",
  "{{alum_first_name}}, formal ask"
 ],
 "z04-c4": [
  "Quick check on the {{role}} referral",
  "Anything you can share?"
 ],
 "z04-c5": [
  "Fellow '26 Husky — practice partner needed",
  "Mock interview trade — {{function}} round"
 ],
 "z04-c6": [
  "Mentorship kickoff — {{your_name}}, MS Analytics '26",
  "Thanks for being matched — agenda for first call?"
 ],
 "z04-d1": [
  "{{first_name}}, 7-day check-in",
  "Following up: {{role}} at {{company}}"
 ],
 "z04-d2": [
  "{{first_name}} — a small update on my {{role}} candidacy",
  "2-week update — {{your_name}}, {{role}}"
 ],
 "z04-d3": [
  "{{first_name}}, last note on {{role}}",
  "30-day final check — {{your_name}}"
 ],
 "z04-e1": [
  "Great speaking with you — {{role}} at {{company}}",
  "Following up on our {{interview_date}} conversation"
 ],
 "z04-e2": [
  "Quick confirmation — next steps for {{role}}",
  "Following up after the {{interview_date}} interview"
 ],
 "z04-e3": [
  "{{recruiter_first_name}}, following up on {{role}}",
  "7-day check-in — {{your_name}}"
 ],
 "z04-e4": [
  "{{recruiter_first_name}}, final check on {{role}}",
  "One last note — {{role}}"
 ],
 "z04-f1": [
  "After your decision — one question",
  "Thank you + one ask"
 ],
 "z04-f2": [
  "6 months later — {{your_name}}",
  "Re-applying after feedback — {{your_name}}"
 ],
 "z04-f3": [
  "After your decision — quick note",
  "Keeping the door open"
 ],
 "z04-g1": [
  "Thanks for the offer — quick timing question",
  "Excited to discuss — next steps?"
 ],
 "z04-g2": [
  "Counter on {{role}} offer",
  "Next steps on {{role}} — proposed adjustment"
 ],
 "z04-g3": [
  "Adjusting the cash component",
  "Final offer conversation"
 ],
 "z04-g4": [
  "Discussion on the equity grant",
  "Long-term alignment via equity"
 ],
 "z04-g5": [
  "Bridge the gap on {{company}} offer",
  "One more proposal — {{role}}"
 ],
 "z04-h1": [
  "Status update — competing offers",
  "Decision timing — {{role}}"
 ],
 "z04-h2": [
  "Quick timing question — {{role}}",
  "Need a few more days — {{role}}"
 ],
 "z04-h3": [
  "Decision update — {{role}}",
  "Thank you and one update"
 ],
 "z04-h4": [
  "Following up on {{company}} offer change",
  "Request to discuss — {{role}}"
 ],
 "z04-l1": [
  "Quick question for a {{target_function}} practitioner",
  "{{first_name}}, would value 15 minutes"
 ],
 "z04-l2": [
  "After our chat — quick recap",
  "Following up on {{chat_date}}"
 ]
};
